### ISSUE TITLE
Small text sizes: Hinting / Grid Fitting / etc

### ISSUE THREAD

**Issue by mattdesl** [nodebox/opentype.js#101]
First off; thanks for this awesome library. :+1: I've added it to my [list of text modules](https://github.com/mattdesl/text-modules).

I am looking for a way to render small glyphs to bitmap tiles with the best possible quality for use in canvas/WebGL rendering. Is this outside the scope of this library? Currently it seems like adding a FT_Render_Glyph binding in [freetype2](https://github.com/ericfreese/node-freetype2) is the only real way I can achieve this in Node.

**Comment by davelab6** [comment]
I think it should be out of scope; that is what freetype is for :)

**Comment by fdb** [comment]
Opentype.js does not do rasterizing. I could imagine a library on top of opentype.js that would take the curves and render them to bitmaps, taking hinting into account.

**Comment by axkibe** [comment]
This can be closed, as been done (for truetype fonts at least)
