### ISSUE TITLE
.ttf exported is not recognised by @font-face

### ISSUE THREAD

**Issue by interactionist** [nodebox/opentype.js#103]
When I export a TTF and try to use it with @font-face, it is not recognised.
Converting the exported TTF to a WOFF makes it usable in @font-face.

**Comment by fdb** [comment]
Is this a font you created from scratch? Or an imported font that you export back out? It would help if you can provide some details about the specific font. If possible, could you send it?

**Comment by interactionist** [comment]
Sure. The font I used is SourceSansPro-Black as TTF taken from the googlefontdirectory. Do you want me to send it via mail? We already chatted via mail btw :)

**Comment by fdb** [comment]
Since it's open source, could you provide a direct link to the font here?

**Comment by miguelsousa** [comment]
@fdb https://github.com/adobe-fonts/source-sans-pro/releases

**Comment by interactionist** [comment]
@fdb Sure. I have it from here: http://www.google.com/fonts#UsePlace:use/Collection:Source+Sans+Pro

**Comment by interactionist** [comment]
I test the subsetting with the different version @miguelsousa provided. Same output.
Worth noting that when checking with the ```isTtf()```the results yields ```false``` for the subsetted version, but ```true```for the original font.

**Comment by fdb** [comment]
Internally we always convert to CFF, since I haven't implemented TrueType exporting yet. 

I think this issue might be related to #103, specifically to half-point numbers being accidentally stored in the (PostScript) font.

**Comment by interactionist** [comment]
So the exported font is actually not a TTF but a CFF, that can be exported as TTF?

**Comment by interactionist** [comment]
When mitigated the rounding errors by using a .otf, see #102. The exported .otf is then not recognised by ```@font-face```even if there are no rounding errors anymore.

When I open the exported .otf in Glphs.app and export another .otf, this one is being picked up by the browsers.

**Comment by fdb** [comment]
There is still something missing in the exported font that makes it fail in the browser. I'm investigating why, since other tools can open it.

WOFF export support is planned, but not yet implemented.

**Comment by interactionist** [comment]
Cool. What I did is: I inspected both font objects (the otf that isn't working, and the otf that works after exported by Glyphsapp) and then I did a diff on those two JSON in Kaleidoscope. Do you want me to send it over? A lot of stuff differs between those two font objects.

**Comment by fdb** [comment]
Sure, send it over. The issue is of course finding out *which* difference actually makes it fail :-)

**Comment by interactionist** [comment]
:) Exactly. I started to compare the font tables, and noticed some differences there. Let me send you the two json files via mail. One finding I had was that the non-working one has an empty ```"subrs":``` in the tables. See screenshot attached.

**Comment by interactionist** [comment]
![diff](https://cloud.githubusercontent.com/assets/527631/6823810/fdb8a61c-d2eb-11e4-8414-5a8bef3ec4ff.png)

**Comment by fdb** [comment]
Subroutines are a way of optimizing font-data by factoring out shared parts between letters (e.g. glyphs for "e" and "é" share a lot of path data) They are not required, though.

Note that exporting a PostScript font does work, so it would be interesting to compare that as well.

**Comment by interactionist** [comment]
> Note that exporting a PostScript font does work, so it would be interesting to compare that as well.

How do you mean? :)

**Comment by fdb** [comment]
- The extension (TTF or OTF) is not a reliable indicator of the internal outline format.
- You can't choose the format to export in opentype.js. Everything is exported as PostScript.
- Fonts such as [Fira](https://github.com/nodebox/opentype.js/blob/master/fonts/FiraSansOT-Medium.otf), which is a PostScript font, do work in the browser.

**Comment by miguelsousa** [comment]
@interactionist Which browsers did you test the exported font with? Chrome and Firefox pre-process the fonts through the [OpenType Sanitizer](https://github.com/khaledhosny/ots). It might be worth testing with this tool to get a sense for what's causing the font to fail.

**Comment by fdb** [comment]
Awesome! Didn't know about OpenType Sanitizer. Will test generated fonts against it.

@miguelsousa do you know other validation tools / linters that I could use to check the generated fonts? The more the better :-)

**Comment by miguelsousa** [comment]
@fdb yes. There's the old [Microsoft Font Validator](https://www.microsoft.com/typography/FontValidator.mspx) that still works for the most part, but hasn't been updated in a long time. And you could also use `compareFamily` which is a tool you can find in [Adobe's FDK](http://www.adobe.com/devnet/opentype/afdko.html).

**Comment by fdb** [comment]
@miguelsousa the MS Font Validator is super-useful, even though it only supports TrueType outlines. Will check out Adobe's tool. Thanks!

The OpenType Sanitizer just shows that a font is "malicious" but there's no additional information. Do you know how I could find out where it fails?

**Comment by fdb** [comment]
OK the MS Font validator found a number of errors. But one that stands out is the difference between (originally) TT and CFF fonts. For TT fonts, the cmap data is not in ascending order. I know not having the correct order caused issues in the past, so this will be my main focus.

**Comment by interactionist** [comment]
@miguelsousa + @fdb You guys rock. I didn't know about those Validators! One thing I noticed also is that there is no font preview with the exported font. But when I reexport with Glyphs it shows me a preview of the font.

@miguelsousa I tested with Chrome and Safari under OSX 10.10.2.

**Comment by davelab6** [comment]
cc @khaledhosny

**Comment by miguelsousa** [comment]
@fdb OTS tends to bit kind of cryptic with its warnings and errors messages, but it usually provides a clue as to in which table the problem is.
MS Font Validator supports OT/CFF fonts as well. It doesn't do the rasterization tests for this font format, but AFAIK it does everything else.

**Comment by khaledhosny** [comment]
Where can I get the font(s) in question? OTS should report why it is rejecting the font most of the time, but it does not always do, but if one built it in the debugging mode (e.g. `make CXXFLAGS=-DOTS_DEBUG`) it should at least shows the lines of code that rejected the font.

**Comment by interactionist** [comment]
@khaledhosny @fdb Do you refer to the one that doesn't work for me?

**Comment by khaledhosny** [comment]
Yes, I’d like to test them myself to see why OTS is rejecting them.

**Comment by interactionist** [comment]
Okay, let me export them for you.

**Comment by interactionist** [comment]
@khaledhosny What is the best way to send you the .zip?

**Comment by khaledhosny** [comment]
@interactionist Email should be fine.

**Comment by interactionist** [comment]
@khaledhosny You should receive a link to download them. This link will expire in 1h.

**Comment by khaledhosny** [comment]
@interactionist using the `ot-sanitise` too, the SourceSansPro-Black.otf (is that the original?) passes just fine, but SourceSansPro-Black-Subset.otf because `cmap` segments are not in ascending order, and it reports it:
> ERROR: cmap: Out of order end range (32 <= 115)
ERROR: cmap: failed to parse table
Failed to sanitise file!

**Comment by khaledhosny** [comment]
BTW, if you are testing the fonts in Firefox, you should get similar messages in the web console.

**Comment by fdb** [comment]
@khaledhosny thanks for confirming this. I'll look into the cmap ordering.

**Comment by interactionist** [comment]
Cheers! Works like a charm.

**Comment by fdb** [comment]
I'll make a release soon, just want to fix the anti-aliasing bug in #102.

**Comment by interactionist** [comment]
Nice. I'll just create a fork and will look into WOFF support.

**Comment by nordisk** [comment]
I just encountered this bug again #155
