### ISSUE TITLE
Can't open my font

### ISSUE THREAD

**Issue by kuckir** [nodebox/opentype.js#104]
Hi, opentype.js can not parse my font  http://www.ivank.net/BRUSHSTP.ttf
It is because there is no "cmap" table. But other programs can work with this font perfectly.

Where is the problem? Can you fix it?

**Comment by fdb** [comment]
The problem is that there's no cmap table :-)

What program did you use to make the font?

**Comment by fdb** [comment]
Actually, I checked: there is a cmap table, but it contains a format we don't support (platformID 1, encodingID 0).

Currently we only support fonts that have cmap tables containing a platformID 3, encodingID 1 or 0 subtable. This is Microsoft's format for Windows, which supports Unicode values.

Apple's [own TrueType documentation](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6cmap.html) discourages the use of the Apple platformID:

> Note that the use of the Macintosh platformID is currently discouraged. Subtables with a Macintosh platformID are only required for backwards compatibility with QuickDraw and will be synthesized from Unicode-based subtables if ever needed. 

I would suggest opening the font in FontForge or FontLab and re-exporting; that should add the correct cmap table.

Support for all cmap formats is a long-term goal, but I can't provide a timeline on when that's going to happen. Issue #105 tracks this.

**Comment by kuckir** [comment]
It seems strange, when opentype.js is supposed to read and write font files, but you recommend other software.

Can you make opentype.js read platform 1 encoding 0 as if there was a 3-1 instead? I.e. convert 1-0 into 3-1 while parsing, and then just continue like nothing happened. I think there are plenty of fonts, which are not "aware" of what Apple considers as "traditional". It would be very useful.

**Comment by fdb** [comment]
Sure, but it still requires a parser for the specific encoding, which we don't have. 

However, since the Apple `cmap` format 0 is so simple, I'll see if I can add it soon.

**Comment by Pomax** [comment]
there are in fact almost no fonts that still use 1/0 (No one's making them anymore, and even those that traditionally use that setting have been moved to a modern unicode cmap). Technically you can't just pretend cmap format 0 is another format, they're all [rather quite different](http://www.microsoft.com/typography/otspec/cmap.htm), but format 0 is terribly simply: it pretends 256 characters is plenty of glyphs in a font, and just straight up contains the list of 256 glyph-to-index mappings. If you font does not contain 256 glyphs, then this is definitely the wrong cmap version to go with, and fdb's advice is worth following: open the tool you used to make your font, and re-export it using a modern format instead (or if it can't, open it in fontforge or something, and then regenerate it)

**Comment by fdb** [comment]
I'm going to agree with @Pomax: I don't think it makes sense to increate the code size of opentype.js for a completely obsolete format. 

We're thinking about adding plugins for parsing, though. When we have this, it might make sense to add plugin support for the format, so we can avoid having it in core.
