### ISSUE TITLE
relative position of baseline in font height

### ISSUE THREAD

**Issue by jardakotesovec** [nodebox/opentype.js#110]
Is there trick how to get relative position of baseline within font height? For example when I set fontSize as 50px - I would like to know where the baseline sits. I can imagine that I can get yMax and yMin if I calculate metrics for all glyphs in font, but I hope for something faster.

Thanks!

**Comment by fdb** [comment]
Glyphs are always placed on the baseline (also called the origin), so you need to subtract the ascender to get at the top corner. For that you could use the ascender, available as `font.ascender` (or also `font.tables.hhea.ascender`). Use that value together with `font.unitsPerEm` to get the value for your font size:

    var top = font.ascender / font.unitsPerEm * 50;

**Comment by jardakotesovec** [comment]
Thanks!

**Comment by villanus** [comment]
Is there a way to get the height and width of a path?
lets say i write the words:
"example" 
"Example"
"ooo"

All of them would have different heights given a specific font.

**Comment by fdb** [comment]
@villanus This is different from the height of a line of text. What you want is the bounding box of an SVG path. I know you're already aware of #124, I'm posting this for future reference.

**Comment by villanus** [comment]
Thanks. I am using SVG.js to to a similar thing.  
Thanks again!

**Comment by nazikus** [comment]
@fdb I'm trying to achieve pixel-precise positioning of text baseline. I tried the way you have mentioned `font.ascender / font.unitsPerEm * 50` but it didn't work, always seems to be few pixels off (varying). 

Also, if I got W3C standard right, they add half-lead to the top ([Leading and half-leading](https://www.w3.org/TR/CSS2/visudet.html#leading)). But again, it doesn't hold whenever i'm increasing font size or line height. You can see it on [Codepen here](http://codepen.io/nazikus/pen/WxzgaQ). Am I doing something wrong? Or any suggestions how to solve this?
Thanks

**Comment by microSoftware** [comment]
Same problem. Try to get the baseline relatively. font.ascender / font.unitsPerEm * fontsize is not too bad but there is always pixel off
Any idea ?

**Comment by wentin** [comment]
I had the same issue, baseline = font.ascender / font.unitsPerEm * fontSize did not work with my example fonts. I found out that the issue is that for these fonts, unitsPerEm != ascender - descender
I wrote about my finding and solution in here: https://malachite-blouse-4fb.notion.site/Font-Metrics-Baseline-Position-4696c45ae4004bc786395d5edd8e387e
