### ISSUE TITLE
Add export support for ligatures.

### ISSUE THREAD

**Issue by fdb** [nodebox/opentype.js#113]
Support specifying ligatures using `GSUB`.

**Comment by Jolg42** [comment]
@fdb Hi! Do you know if someone is working on it ?

**Comment by fdb** [comment]
I don't think anyone is. Do you know anyone who would like to work on it? I'd be glad to show them around the codebase.

**Comment by Jolg42** [comment]
@fdb Sorry for my late response. So how do you estimate the time / effort on this feature ? Because I will be interested to work on it or sponsor someone to do it.

**Comment by Jolg42** [comment]
@fdb Do you have an idea about my last question ?

**Comment by fdb** [comment]
Every estimate depends on who is going to do the work. I'm not familiar with the GSUB tables as well. This code was written by other people, mostly @fpirsch and @moyogo. 

A conservative estimate would be around 2-3 weeks, if you've never seen the codebase. 

Unfortunately, I'm in my final PhD year and have no time to work on a bigger feature like this myself. I hope you can understand.

**Comment by Jolg42** [comment]
Note: The GSUB table is now available, thanks to @fpirsch work (sponsored by my company, Fontself) 👍
