### ISSUE TITLE
Exporting fonts must set UPM=1000, even if their UPM is higher than that.

### ISSUE THREAD

**Issue by mattlag** [nodebox/opentype.js#115]
Ran into a bunch of issues when trying to export a font where it looked like the letter spacing and line height / bounding box were all messed up:

![image](https://cloud.githubusercontent.com/assets/5897669/7619748/a6464d3a-f96f-11e4-912a-feca0defabf9.png)

Finally figured it out that the setting options.unitsPerEm = 1000 *regardless of the font's UPM* solved the issue:

![image](https://cloud.githubusercontent.com/assets/5897669/7619780/db4b8d88-f96f-11e4-908d-9a8c2f2090ea.png)

This is Merriweather Sans with a UPM of 2048, but exported at 1000.

Also, the blinking cursor seems to be the right height, but the selection area seems to be too small:

![image](https://cloud.githubusercontent.com/assets/5897669/7620262/87d271b8-f973-11e4-910d-cd9cf128d37d.png)

I'm on Windows, I tried this out in PowerPoint, Word, and Adobe Illustrator.

**Comment by fdb** [comment]
Thanks for the detailed report Matt; I'll look into it next week.

**Comment by rkusa** [comment]
I seem to have the same issue. I am playing with replacing my own font implementation in [pdfjs](https://github.com/rkusa/pdfjs) with opentype.js. Chrome, Firefox (pdf.js) and Mac Preview are displaying the font correctly, however, Adobe Reader messes it up:

![screen shot 2015-05-20 at 10 08 24](https://cloud.githubusercontent.com/assets/409021/7721511/7778c834-fed8-11e4-9197-c2d559f4390a.png)

Please let me know if I can do anything helping to track down this issue.

**Comment by fdb** [comment]
@rkusa That's weird -- can you send me the font + code you used to generate this?

**Comment by mattlag** [comment]
I thought I'd add this as well -

Here is my font export code:
https://github.com/mattlag/Glyphr-Studio/blob/master/dev/js/io_otf_export.js

Which relies heavily on the Glyph object:
https://github.com/mattlag/Glyphr-Studio/blob/master/dev/js/obj_glyph.js

I first encountered this, and documented a lot of details in this bug:
https://github.com/mattlag/Glyphr-Studio/issues/176

In the process I used TTX to investigate the exported OTF, but couldn't see anything that would cause problems (but, I'm rather novice at the full implications of OTF table values).  All the postscript code for the glyphs was exported correctly. @davelab6 did a TTX diff of Merriweather Sans original vs. Merriweather Sans exported through Glyphr Studio:
https://github.com/davelab6/example-bellweather/pull/1/files?diff=split

So, hopefully this helps.

**Comment by fdb** [comment]
@mattlag thanks so much! I'll investigate and let you know.

**Comment by fdb** [comment]
I've tracked the bug to the CFF fontMatrix, which defines an affine transform for the glyph outlines. The fontMatrix defaults to `[0.001 0 0 0.001 0 0]`which works fine with fonts with a UPM of 1000. Other fonts need to set the matrix to a different scale value, e.g. fonts with a UPM of 2048 use 1/2048 = 0.000488281. 

OpenType.js didn't set the fontMatrix anywhere, and so all fonts used the default font matrix, which is only suitable for fonts with a UPM of 1000.

I now create a fontMatrix based on the unitsPerEm.

Thanks @mattlag and @davelab6 for helping me find the bug. Especially the  TTX export helped in tracking down the bug.

**Comment by mattlag** [comment]
Awesome - thanks! I'll update to 0.4.7 and let you know if anything goes wrong.

**Comment by fdb** [comment]
@mattlag please use version 0.4.8, which I just pushed (and includes the fix).

**Comment by mattlag** [comment]
Great - will do. Thanks.
