### ISSUE TITLE
font.toBuffer() crashes due to the presence of an undefined element in the strings list

### ISSUE THREAD

**Issue by felipesanches** [nodebox/opentype.js#122]
The bug was fixed in the in-tree copy of opentype.js used in Metapolator:
https://github.com/felipesanches/metapolator/commit/003d95c330ef9828056c7754567adf55d04ed1bf

This is a report in the hope the issue gets fixed upstream as well.

**Comment by Jolg42** [comment]
Quoted from #123 

> In the absence of a test case, closing this PR and revisiting once someone runs into this again will probably be better than keeping this PR open or, far worse, merging it in without a test case to tie it to. Someone will eventually hit this again.

**Comment by davelab6** [comment]
@Jolg42 did you review the fix made downstream?

**Comment by Jolg42** [comment]
@davelab6 This fix https://github.com/felipesanches/opentype.js/commit/e17a2d0f32fd8b50775eba47c0613c4fcbc3f127 ?
In the issue #123 we were thinking that without a test case we will wait before merging it.
