### ISSUE TITLE
Passive font loading?

### ISSUE THREAD

**Issue by Pomax** [nodebox/opentype.js#129]
I tried to use OpenType.js to load a set of nine Japanese fonts (think 13500ish glyphs per font) totaling less than 50 MB on disk, and was rather surprised to see memory grow to 1625MB before Node.js crashed with a memory allocation failure error =)

To explain how disastrous the full load really is: normally you want to memory map a big font, and then only do glyph outline fetching when those glyphs are necessary for text shaping. If you don't a 6MB font like Ume Minchou turns into 320MB of fully unpacked object. That means you can't even load three, or even two fonts, on the most cost effective common VPS hosts (digital ocean, vultr, etc)

Is there a way to make OpenType.js passively load a font so that it doesn't build the full font object until it actually needs the parts that are revealed necessary due to function calls? Even loading in everything except the glyph data (only loading that in when it's actually necessary for text shaping calls) should save well over a gig of memory, making loading many fonts a lot more tractable.

**Comment by Pomax** [comment]
I had a look at where this would require changes, by turning the font.glyphs array into a GlyphSet object with deferred parsing, but you're using the total glyph list in *a lot* of places to further load data. Probably still worth doing, since the switch from array to deferred loading won't change how the font behaves and will allow progressive improvement of the code once landed, but it looks like a lot of code was written in the assumption that fonts fit entirely in memory, which hasn't been true for a long time =(

**Comment by yurenju** [comment]
This issue looks related to #126, looks like the same issue.
