### ISSUE TITLE
Can opentype display .fon fonts?

### ISSUE THREAD

**Issue by phoenicyan** [nodebox/opentype.js#133]
I'm looking for a way to display both .ttf and .fon fonts. Is it possible?

**Comment by Pomax** [comment]
Opentype.js is for loading OpenType fonts, so it will happily load `.ttf` (The "TrueType" variant) and `.otf` (The CFF/"Type2" variant) fonts. Fonts with the `.fon` extension are a really old bitmap format (they're Windows executables with a 16 bit image inside of them) and are not supported by Opentype.js
