### ISSUE TITLE
glyph-inspector: CFF/OTF glyphs are loaded after they need to be displayed

### ISSUE THREAD

**Issue by moyogo** [nodebox/opentype.js#140]
In the glyph-inspector example page, the pagination doesn’t load the glyphs outlines before they are displayed for CFF/OTF fonts. They are only visible after reloading the pagination page. This happens since #131.

**Comment by cyrilcoutelier** [comment]
I don't know if this is related, but I had a similar issue. 
I was doing
```javascript
var glyphIdx = font.charToGlyphIndex(char);
if (glyphIdx !== null) {
    var glyph = font.glyphs[glyphIdx];
    // awesome stuff
}
```
and now I have to do
```javascript
var glyph = font.charToGlyph(char);
if (glyph !== null) {
    // awesome stuff
}
```

**Comment by moyogo** [comment]
@fdb I can still reproduce the bug when opening an OTF in glyph-inspector.html.

**Comment by fdb** [comment]
Locally or on opentype.js.org? I forgot to update the gh-pages, I'll do that now.
