### ISSUE TITLE
support In IE 9 browser

### ISSUE THREAD

**Issue by mukeshcp** [nodebox/opentype.js#156]
Hi,
does Opentype js work on IE9 browser?

while run opentype js in IE browser,It gives error :   SCRIPT5009: 'DataView' is undefined 

Any alternate way?

**Comment by fdb** [comment]
OpenType.js uses typed arrays. They're implemented starting from IE10:

http://caniuse.com/#feat=typedarrays

They're the way we operate on the data, so it's not trivial to replace them with something else. 

I saw there was a polyfill for them, but haven' t tested it: https://gist.github.com/Benvie/5020656

You could try to load that code before opentype.js and see if it works.

**Comment by pranavcp** [comment]
If i integrate polyfill.js, it stops execution on line number 369
at
      if (!(buffer instanceof ArrayBuffer)) {
        throw new TypeError('DataView must be initialized with an ArrayBuffer');
      }

any reason?
