### ISSUE TITLE
Glyph .getPath does not return all the sub-paths from composite glyphs

### ISSUE THREAD

**Issue by create3000** [nodebox/opentype.js#158]
If I call getPath on a glyph, it does not return all the sub-paths.

The workaround is to manually collect all sub-paths from the glyphs components:

				if (glyph .isComposite)
				{
				   for (var c = 0; c < glyph .components .length; ++ c)
				   {
				      var component = glyph .components [c];

				      paths .push (font .glyphs .get (component .glyphIndex) .getPath (component .dx / font .unitsPerEm, component .dy / -font .unitsPerEm, 1));
				   }
				}
				else
				   paths .push (glyph .getPath (0, 0, 1));

**Comment by fdb** [comment]
What do you mean exactly? All the points should be there, merged together.

If that's not what you want, you can use Glyph.getContours(), which will return a list of contours.
