### ISSUE TITLE
OTF files generated by Metapolator are rejected by Apple's validator

### ISSUE THREAD

**Issue by felipesanches** [nodebox/opentype.js#159]
Metapolator is using OpenType.js to output OTF files.
We got a new issue filled in our issue tracker that may actually be an OpenType.js bug, so I'm referencing here in case the fix needs to be implemented upstream.

The original issue is filled here: https://github.com/metapolator/metapolator/issues/649

**Comment by fpirsch** [comment]
Hi,
just tried to validate an opentype.js generated font with Microsoft Font Validator, and got these:

OS/2 table
* The usFirstCharIndex is not valid (actual = 0x0000, calculated = 0x0041)
* The usBreakChar is not mapped to a glyf (0x0020)

hhea table
* The Descender value must be less than zero Descender = 0 

post table
* The isFixedPitch field is zero, but hmtx shows the font as fixed pitch

This could be a start.

**Comment by fdb** [comment]
I read the Metapolator bug report. I don't really want to guard against illegal names in the font, but I want to look at the other tables.

I've used [ots](https://github.com/khaledhosny/ots) in the past to ensure fonts were valid. I'd love to check if there were any regressions.

Could you send the test font to me?

**Comment by fdb** [comment]
I haven't tested this with Metapolator, but in my testing generated fonts now work well on OS X. 

I've added examples on how to generate fonts in the examples/ folder, e.g. `examples/generating-font-node.js` (this is for node.js, but works almost exactly the same in the browser).

**Comment by fdb** [comment]
Sorry, forgot to mention: this is with opentype.js version 0.6.0.

Please let me know if it works for you, so I can close this issue.

**Comment by Jolg42** [comment]
I think this issue can be closed?
Btw I just fixed the usFirstCharIndex and it was merged in master ;)

**Comment by fdb** [comment]
Yep! Thanks!
