### ISSUE TITLE
Font validation error on  `name` table with Font Book

### ISSUE THREAD

**Issue by Jolg42** [nodebox/opentype.js#166]
Hi,

I have this problem when I want to install my opentype.js generated font on my MacBook.

<img width="618" alt="screenshot 2015-11-25 15 27 30" src="https://cloud.githubusercontent.com/assets/1328733/11399695/46e17928-9389-11e5-9c99-e4eb02401a5e.png">

There is a problem with the `name` table,

Maybe I need to add some options ?

The font is working but the errors warning are a problem for us :/ We don't want to share font files with theses errors for example.

**Comment by fdb** [comment]
Hi, 

I'm running in to this very same problem myself as well. I'm looking into it.

I've noticed that it is not a problem when re-exporting existing fonts, so I'm trying to bisect the issue to find out which parameters need to be set. However, this is a very tedious process....

**Comment by fdb** [comment]
After some digging, it seems the `fullName` name needs to be set for Font Book to validate the font. Furthermore, if you want Font Book to actually *display* the letters, setting the `postScriptName` is also important.

I'm working on auto-generating these names. However, you can do this yourself right now by just setting the correct names:

    var glyphs = [...];
    var font = new opentype.Font({
        familyName: 'MyFont', 
        styleName: 'Regular', 
        unitsPerEm: 1000, 
        glyphs: glyphs});
    font.names.postScriptName = {en: 'MyFontRegular'};
    font.names.fullName = {en: 'MyFont Regular'};

**Comment by fdb** [comment]
This is fixed in opentype 0.6.0. Also, I've made sure the "Quick Look" preview works as well (related to an internal encoding issue).

**Comment by Jolg42** [comment]
@fdb Great! :+1: Thank you! It's working for me too :)
