### ISSUE TITLE
Validate newly created fonts to check that advanceWidth is set

### ISSUE THREAD

**Issue by louisremi** [nodebox/opentype.js#167]
I updated the opentype.js that powers plumin.js (and prototypo.js, and Prototypo), and then all fonts that we generated couldn't be loaded in the browser.

It took me quite some time to realize that [glyphToOps](https://github.com/nodebox/opentype.js/blob/master/src/tables/cff.js#L950) was tweaked some time ago and that an `advanceWidth` property was now required for every glyph, including `.notdef`.

I was wondering if opentype.js should throw an error in such case, which would make debugging problematic fonts much easier (the errors reported by the browser, FontForge and even OTS are rather cryptic).

**Comment by fdb** [comment]
You're absolutely right: we should validate the input data, since there is no useful output data we could generate.

I'll update the bug title to reflect that we want a validation step.
