### ISSUE TITLE
Ascender & Descender are required in 0.6.0 - Why?

### ISSUE THREAD

**Issue by Jolg42** [nodebox/opentype.js#169]
Hi @fdb 

I was wondering why theses values `font.ascender & font.descender` are required because I found that when exporting the font, if font.ascender is not defined for example the yMax is computed on all glyphs (so it is more accurate I think) https://github.com/nodebox/opentype.js/blob/0.6.0/src/tables/sfnt.js#L193

**Comment by moyogo** [comment]
@Jolg42: yMax is the y coordinate of the tallest glyph while font.ascender represents the top of the line height (another metric can represent the typographic top of letters with ascender, useful when aligning things). These are not necessarily the same, in most fonts they aren’t.

Suppose you have one off symbol that is really tall and it’s top provides the yMax, you don’t want to use that as a font.ascender. Especially if next time you update your font you add another taller symbol, thus changing yMax. font.ascender and therefore the line height should be stable and should depend on the overall design of a font not a a single glyph.

**Comment by Jolg42** [comment]
@moyogo Yes, Thank you for the explanation, I see the difference :) So maybe we can clean the code because ascender & descender are now required and can't be undefined ?

https://github.com/nodebox/opentype.js/blob/0.6.0/src/tables/sfnt.js#L193
```js
    globals.ascender = font.ascender !== undefined ? font.ascender : globals.yMax;
    globals.descender = font.descender !== undefined ? font.descender : globals.yMin;
```

to

```js
    globals.ascender = font.ascender;
    globals.descender = font.descender;
```

What do you think ?

**Comment by fdb** [comment]
I've made this change because this kind of guessing magic always comes back to bite me (and you as well, probably). Also, it causes errors when exporting fonts if you're not careful (for example, when subsetting fonts).

Simplifying the code a bit is a good option, yes.
