### ISSUE TITLE
got errors when try to exec the samples

### ISSUE THREAD

**Issue by megaghz** [nodebox/opentype.js#170]
cd examples
npm start
> opentype.js@0.6.0 start /Users/me/Sites/opentype.js
> mkdirp build && parallelshell "npm run watch" "node ./bin/server.js"

sh: mkdirp: command not found

**Comment by fdb** [comment]
I just checked and `mkdirp` is specified in the `package.json`'s `devDependencies`. Maybe try `npm install` again (older versions didn't use mkdirp)?
