### ISSUE TITLE
Specifying OS2 values for weight, width and fsSelection

### ISSUE THREAD

**Issue by FranzPoize** [nodebox/opentype.js#176]
Hi,

I would be cool to be able to choose this value during the fontToSfntTable function (right there https://github.com/nodebox/opentype.js/blob/master/src/tables/sfnt.js#L220).

I gonna make a PR to go with this issue.

**Comment by fdb** [comment]
Yes I agree. Ideally you would be able to provide the full configuration of the table (of all tables, really).

**Comment by FranzPoize** [comment]
Here is what I came up with. I'll wait for the problem with the last PR to be resolved and create the PR for this issue.

https://github.com/FranzPoize/opentype.js/commit/46afef8bf794b0d5b9bad1f16609ad6c7beb93a4

**Comment by chearon** [comment]
I need this too, I'm not sure why it can't get the values from the font object when `toArrayBuffer` is called. That's what I'd expect

**Comment by fdb** [comment]
@FranzPoize problem with other issue is fixed -- so if you can make a PR I can look at it.

The issue that's bothering me (not with this code, with OTF in general) is that the value is duplicated in a number of places. Ideally there would be a single master "width" setting that would then get applied to the different tables.

**Comment by FranzPoize** [comment]
@louisremi is currently looking at my work and trying to make it work with parsed otf file (my commit had trouble with these) and we'll make a PR when our code is ready.

I think one problem with having one master is that when parsing you can't assume otf file will have the correct values everywhere I guess. On our side we don't really care and we could make it work with only a master width but we currently only needs those value so that Windows can differentiate our font in its font library :D

Thanks for merging the other :smile:

**Comment by Jolg42** [comment]
Merged with #199
