### ISSUE TITLE
font-inspector: cmap.glyphIndexMap always appears as [object Object]

### ISSUE THREAD

**Issue by Artoria2e5** [nodebox/opentype.js#178]
For example, the default font file on https://nodebox.github.io/opentype.js/font-inspector.html.

**Comment by fdb** [comment]
Yes, there is no decoder yet for that part of the structure. We should add one.

**Comment by fdb** [comment]
Code is here for reference: https://github.com/nodebox/opentype.js/blob/master/font-inspector.html#L147 (and if you want to hack on it yourself)

**Comment by Arthur2e5** [comment]
`` `<pre>${JSON.Stringify(value, null, 2)}</pre>` ``works but looks absolutely absurd…

I should make a collapsible `<dl>`…

**Comment by Mottie** [comment]
I just realized that the PR I made yesterday (#192) fixes this issue.

**Comment by fdb** [comment]
It works but it could look better 😄 

![screen shot 2016-06-20 at 10 37 43](https://cloud.githubusercontent.com/assets/8477/16187871/0c01a3da-36d3-11e6-92ae-6594d163846e.png)

**Comment by Mottie** [comment]
You could update the css to make the block scrollable:

```css
#font-data dd {
    margin-left: 12em;
    word-break: break-all;
    max-height: 100px;
    overflow-y: auto;
}
```

![2016-06-20 13_05_42-opentype js font inspector](https://cloud.githubusercontent.com/assets/136959/16205168/328afa1e-36e8-11e6-998b-affd9d7eb839.png)

**Comment by fpirsch** [comment]
Still, it could look better ;-)
Do we really need to display hundreds or thousands of indexes here ? What for ? What would be the best view to make it easy to find useful information ?

**Comment by fdb** [comment]
The best way might be to add extra info to the glyph inspector: to show the unicode mappings for every glyph index.

The question is what you would want to do with the information. The glyph index map is not the "raw" data stored in cmap. Cmap stores a number of segments -- maybe it's more useful to show those here, with hyperlinks to the correct glyph.

**Comment by fdb** [comment]
@Mottie I've added the scrolling CSS tweak to make the view a bit more palatable. Thanks!
