### ISSUE TITLE
Qustion: - What is the proper way to get measurements of an SVG Path

### ISSUE THREAD

**Issue by villanus** [nodebox/opentype.js#186]
I have loaded a ttf font, and created a path using the path.toSvg method.

now I am trying to figure out how to measure the size of the path using either Jquery of vanilla javascript.   When I load the path into an empty svg, I am not able to get the height or width. 

What is the proper way to do this?

After 3 hours, I am still confused :8ball:

**Comment by Silverwolf90** [comment]
You could give this a shot?

https://github.com/icons8/svg-path-bounding-box

**Comment by villanus** [comment]
i am trying to do this in the browser not node

**Comment by fdb** [comment]
Closing, as this is a duplicate of #124.
