### ISSUE TITLE
Variable `btype` leaked to global scope (`btype` is not declared)

### ISSUE THREAD

**Issue by cuixiping** [nodebox/opentype.js#189]
Recently I wrote a tool to check all global variables in all javascript files of my project, and find that opentype.js leaked a `btype` variable. 

I can see the following code in [dist/opentype.js](https://github.com/nodebox/opentype.js/blob/master/dist/opentype.js)

```
function tinf_uncompress(source, dest) {
  var d = new Data(source, dest);
  var bfinal, res;

  do {
    /* read final block flag */
    bfinal = tinf_getbit(d);

    /* read block type (2 bits) */
    btype = tinf_read_bits(d, 2, 0);
```

obviously, `btype` is not declared and will  leak to global scope.

It's caused by [tiny-inflate](https://github.com/devongovett/tiny-inflate), but tiny-inflate has fixed it ([see commit](https://github.com/devongovett/tiny-inflate/commit/64c3e193e9f7c5c4a2110a3bc5407640569858d7)), opentype should update and remake the dist files.

**Comment by fdb** [comment]
Thanks for reporting this! I've upgraded the dependency and released a new version.
