### ISSUE TITLE
Ligatures

### ISSUE THREAD

**Issue by casperno** [nodebox/opentype.js#194]
Hi,

I've spent some time with opentype, using it to load fonts used in txt.js. It was surprisingly easy, but I miss ligatures.

From what I can see in the code, opentypejs uses GPOS tables for kerning values. Isn't the GPOS also the table for ligatures? Anyone working on this now? If not, any pointer for me if I find the time to try and implement it?

Thanks to all developers for an amazing feat - if it wasn't for the obvious proof that it's working, I wouldn't have believed that parsing of binary font data was feasible in javascript

**Comment by fpirsch** [comment]
Hi casperno,
I wrote the GPOS code, and I am currently working on the GSUB which stores ligatures and other interesting features. I will submit some pull requests before the end of the month to support GSUB reading and (partial) writing.

**Comment by casperno** [comment]
Fantastic! Looking forward to it.

**Comment by fdb** [comment]
Hey @fpirsch that's great news! Let me know if I can help.

**Comment by fpirsch** [comment]
#200 Adds full GSUB parsing. Writing simple cases coming soon.

**Comment by Harbs** [comment]
This is amazing! How would you go about using the tables for specific features (like rlig, liga, onum, salt, etc.)? Is that implemented yet? If not, what are your thoughts on implementation?

**Comment by fdb** [comment]
@fpirsch amazing work!

**Comment by fpirsch** [comment]
@Harbs The GSUB data is exposed through the `font.tables.gsub` object. I'm now working on a `Substitution` object, made available as `font.substitution`, carrying all the methods needed to list, search and edit this data (for the most common features).

**Comment by Harbs** [comment]
I'm not sure what other APIs look like. The FTE model is one that makes sense to me.
http://help.adobe.com/en_US/ActionScript/3.0_ProgrammingAS3/WS56773E36-AC97-4047-B9C1-D9DFA9A51F3F.html
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/TextElement.html
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/text/engine/ElementFormat.html
Some similar API seems ideal. I like that opentype.js is finer grained than FTE.

**Comment by Harbs** [comment]
@fdb To be clear, I was not suggesting a full FTE-type implementation. I'd love for someone to do my work for me, but I expect to have to do that myself... ;-)

I was rather suggesting some type of object similar to ElementFormat where you could specify features for a run of text and get back Glyph objects which match the feature set.

Something like: `Font.stringToGlyphs(string,format)` instead of `Font.stringToGlyphs(string)`

It would make a lot of sense for at least this functionality to be in the core library.

**Comment by fpirsch** [comment]
@fdp I'm about to submit a new PR where the API looks like
`font.substitution.getLigatures()`
`font.substitution.addLigature({sub: [42, 42, 45], by: 167})`
Glyphs are referenced by id. Using their names would require some more work in the GlyphSet I suppose.
`font.gsub` could be confusing with the actual GSUB data `font.tables.gsub` which does not always exist, so I went for `font.substitution`.
This is a start, it could use some polish later.

**Comment by Harbs** [comment]
I'd rather change the API a bit. Instead of `font.substitution.getLigatures()` I think `font.substitution.getFeature('liga')` makes more sense. There's at least three features related to ligatures alone (i.e. rlig, liga, dlig) not to mention the plethora of other GSUB features. It might also make sense to have `font.substitution.getFeatures(['liga','rlig'])` which would aggregate the subsitutions of multiple features.

Likewise, `font.substitution.addLigature({sub: [42, 42, 45], by: 167})` should probably be `font.substitution.addSub("liga",{sub: [42, 42, 45], by: 167})`
Does this make sense?

**Comment by fpirsch** [comment]
@Harbs You're right. I was focused on standard ligatures, but a more generic approach by feature name make more sense. So let's stick to `font.substitution.getFeature('liga')`.
And maybe `font.substitution.add("liga",{sub: [42, 42, 45], by: 167})` could do the job ? `font.substitution.addSub("liga",{sub: [42, 42, 45], by: 167})` feels like there's a lot of "sub".

**Comment by Harbs** [comment]
Sure. "add" sounds better.

One thing that's going to be important to think about is the **order** of substitutions. There's lots of complex fonts which have really complex tables where the order is critical for correct rendering of text. I'm not sure the best way to handle that, and "one thing at a time", but I figured it does not hurt to mention the issue... The is really awesome stuff! :-)

**Comment by fpirsch** [comment]
My idea was to stay low-level and simply append new substitutions. This leaves the problem of ordering to the application.

**Comment by Harbs** [comment]
The order is programmed into the font. The application has no way of knowing the correct order unless the info is presented in an informative way.

One possible way to solve this problem would be to allow `font.substitution.getFeatures(['liga','rlig'])` like I mentioned above and the list of substitutions would reflect the table order in the font (not the order of features as requested).

**Comment by davelab6** [comment]
I wonder if CSS3 feature strings could be helpful,
https://www.w3.org/TR/css-fonts-3/#propdef-font-variant

**Comment by casperno** [comment]
I've updated opentype.js in my project and implemented support for ligatures. THANK YOU! As a typography nerd, this makes me very happy.

The `getLigatures` does what it says, but returns a result that isn't very fast to use for lookups.  So I've wrote a new function that returns a lookup table, structured much like the opentype font.
Is this something you'd feel comfortable adding to the main project?

Usage:
```
var ligLookup = fnt.substitution.getLigatureLookup('liga');
var fiGlyph = ligLookup['f']['f].glyph
```

```
   Substitution.prototype.ligLookup = null;

            Substitution.prototype.getLigatureLookup = function(feature, script, language) {
                script = script || 'DFLT';
                language = language || 'DFLT';

                if (this.ligLookup)
                    return this.ligLookup;
                var ligLookup = {}
                var lookupTable = this.getLookupTable(script, language, feature, 4);
                if (!lookupTable) {
                    return ligLookup;
                }
                var subtables = lookupTable.subtables;
                for (var i = 0; i < subtables.length; i++) {
                    var subtable = subtables[i];
                    var glyphs = this.expandCoverage(subtable.coverage);
                    var ligatureSets = subtable.ligatureSets;
                    for (var j = 0; j < glyphs.length; j++) {
                        var startGlyph = glyphs[j];
                        var fontGlyphs = this.font.glyphs.glyphs;
                        var firstChr = fontGlyphs[startGlyph].name;
                        ligLookup[firstChr] = {};
                        var ligSet = ligatureSets[j];
                        for (var k = 0; k < ligSet.length; k++) {
                            var lig = ligSet[k];
                            var child = ligLookup[firstChr];
                            var ligCmps = lig.components;
                            for (var l = 0; l < ligCmps.length; l++) {
                                if (child[fontGlyphs[ligCmps[l]].name] == undefined)
                                    child[fontGlyphs[ligCmps[l]].name] = {};
                                if (l < ligCmps.length - 1)
                                    child = child[fontGlyphs[ligCmps[l]].name];
                            }
                            child[fontGlyphs[ligCmps[l - 1]].name].glyph = fontGlyphs[lig.ligGlyph];
                        }
                    }
                }
                this.ligLookup = ligLookup;
                return ligLookup;

            }
```

**Comment by Harbs** [comment]
Good idea, but I'd take it one step further. Instead of getLigatureLookup, I'd make it "getFeatureLookup" to make it generalized, and it would have a hastable of the previously requested features.

**Comment by casperno** [comment]
Good thinking. I see that getFeature is implemented this way. 
How do you feel about the results being cached in `Substitution.prototype.ligLookup`? 
Should it be cached by the code using it instead? Or is the additional memory footprint negligible?

**Comment by fpirsch** [comment]
Hi @Casperno, you're right the `getLigatures` method is not intended for fast rendering lookups, but for font edition purposes.
IMHO the best lookup structure for this would be the raw font data in `font.tables.gsub`. I don't think there is a need to build an additional structure. In particular, `expandCoverage` is handy but not efficient. Instead, we need fast search methods in the raw data.
Of course the fastest way would be to search directly the binary data.

**Comment by Harbs** [comment]
I did not quite get exactly what expandCoverage does. (I was actually trying to figure out the logic inside substitutions today.) Can you explain?

**Comment by Harbs** [comment]
BTW:
I'm not sure I'm reading the code correctly, so I might have missed it, but did not see where ligature lookup sorting was taking place.

According to the spec:
  sub f f by f_f;
  sub f i by f_i;
  sub f f i by f_f_i;
  sub o f f i by o_f_f_i;

will produce an identical representation in the font as:

  sub o f f i by o_f_f_i;
  sub f f i by f_f_i;
  sub f f by f_f;
  sub f i by f_i;

For the substitutions to work correctly in all cases, someone needs to do the sorting. I'm not sure if the sorting should happen when the type 4 tables are initially parsed or at some later point. (It makes the most sense to me to do a one time lazy sorting, the first time the type 4 tables are accessed.)

Thanks.

**Comment by casperno** [comment]
You're quite right, the sorting is not done in the supplied code. Basically, if a char has ligatures at all, we look forward four characters, try first looking up with all four, then three, then two. 

I kept that part out of opentypejs, as it seem more of an layout implementation problem than.

**Comment by Harbs** [comment]
That seems pretty inefficient, but I'm not sure there's a better way.

I'm probably going to implement a caching mechanism for words so I only have to do the lookups on a particular word once.

**Comment by Harbs** [comment]
Another question I'm having trouble figuring out:

Are glyph classes and glyph ranges supported? It seems they would need to be (for GPOS as well), but I couldn't find it.

Any pointers would be very welcome.

**Comment by Harbs** [comment]
FYI:
While brushing up on my OpenType, I came across this post:
http://ansuz.sooke.bc.ca/entry/131

Very useful observations there.

I found that bit towards the end about named lookups very interesting as well. It's important to know where the named lookup is declared for implementation purposes.

**Comment by fpirsch** [comment]
@Harbs `expandCoverage` unifies both coverage table types (list and range) in a single list. Useful for editors, and that's all.

Glyph classes and ranges are parsed, but not used in the rendering (btw, currently the GSUB table is not used at all in the rendering process). `font.substitution.add` doesn't use them either. If you want to add a substitution with classes or ranges, you'll have to modify directly the `font.tables.gsub` object.

There is no ordering in opentype. `font.substitution.getFeature` lists substitutions in the same order they are in the file. And `font.substitution.add` adds them one by one in the order you provide them. So YOU (the font designer) have to do the sorting you want.

**Comment by Jolg42** [comment]
I'm closing this issue as the first version with ligatures is now working.
The examples are in the tests for now.
If someone have ideas or more advanced need, just open a new issue 😉
