### ISSUE TITLE
Generated fonts don't show up in Apple's font menu

### ISSUE THREAD

**Issue by fdb** [nodebox/opentype.js#198]
It seems OpenType.js doesn't set the correct fields for language and script, which means that OS X doesn't list them in font menus (you can still select the font from the font dialog.

To reproduce:

1. Generate a font, for example by running `node examples/generate-font-node.js`
2. Install the font on OS X
3. In Font Book, show the font info. Note that entries for "Language" and "Script" are missing.
4. In TextEdit, the font is not listed in the font menu.

Screenshot of Font Book:
![screen shot 2016-06-24 at 08 36 18](https://cloud.githubusercontent.com/assets/8477/16330035/bf27ef4e-39e6-11e6-9c97-f8355cc1ab88.png)

Example font:
[Pyramid-Regular.otf.zip](https://github.com/nodebox/opentype.js/files/331304/Pyramid-Regular.otf.zip)

**Comment by fdb** [comment]
Paging @Jolg42 — have you seen this behaviour as well? Any ideas on what could cause it?

**Comment by Jolg42** [comment]
Hi @fdb Yes I have the same behavior here on multiple macbooks…
The font is not showing in the main menu of TextEdit but in the "Show fonts" panel.
Maybe the "Language" and "Script" can help… We have to try!

Btw, we found a special behavior for Mac Pages, which do not show the font in the list if the font is not containing a certain range of characters (ie: a -> z  & numbers)

And also for Word 2008 if the name is too long the font don't show up in the menu, I think I'm gonna put some limits to specifics name fields to improve the compatibility across OS / Apps with references/docs I found.

**Comment by Jolg42** [comment]
I just tried tweaking the OS/2 ulUnicodeRange1 & ulCodePageRange1 with value "1" for Latin like some other Latin fonts and it wasn't doing anything in the FontBook. (it's the only values that can indicate some language support that can be set manually).

But I finally found what the FontBook app is checking!

![screenshot 2016-06-24 at 16 14 09](https://cloud.githubusercontent.com/assets/1328733/16341238/6e94cd5e-3a2c-11e6-8e22-a6313bfdd7fe.jpg)
![screenshot 2016-06-24 at 16 14 40](https://cloud.githubusercontent.com/assets/1328733/16341249/77233d0c-3a2c-11e6-950c-9beb17665eda.jpg)


In fact the app is checking for a list of characters, here is the list that is working for me (I didn't tried to remove chars to check if a subset of this list is still working):

[https://en.wikipedia.org/wiki/Basic_Latin_(Unicode_block)](https://en.wikipedia.org/wiki/Basic_Latin_(Unicode_block))

U+0000 & U+0020-U+007F (97 characters)
- A-Z uppercase
- a-z lowercase
- 0-9
- 0x0 NULL
- 0xd CR
- 0x20  SPACE
- 0x21 ! EXCLAMATION MARK
- 0x22 " QUOTATION MARK
- 0x23 # NUMBER SIGN
- 0x24 $ DOLLAR SIGN
- 0x25 % PERCENT SIGN
- 0x26 & AMPERSAND
- 0x27 ' APOSTROPHE
- 0x28 ( LEFT PARENTHESIS
- 0x29 ) RIGHT PARENTHESIS
- 0x2a * ASTERISK
- 0x2b + PLUS SIGN
- 0x2c , COMMA
- 0x2d - HYPHEN-MINUS (hyphen)
- 0x2e . FULL STOP (period)
- 0x2f / SOLIDUS (slash)
- 0x3a : COLON
- 0x3b ; SEMICOLON
- 0x3c < LESS-THAN SIGN
- 0x3d = EQUALS SIGN
- 0x3e > GREATER-THAN SIGN
- 0x3f ? QUESTION MARK
- 0x40 @ COMMERCIAL AT
- 0x5b [ LEFT SQUARE BRACKET
- 0x5c \ REVERSE SOLIDUS
- 0x5d ] RIGHT SQUARE BRACKET
- 0x5e ^ CIRCUMFLEX ACCENT
- 0x5f _ LOW LINE (underscore)
- 0x60 ` GRAVE ACCENT
- 0x7b { LEFT CURLY BRACKET
- 0x7c | VERTICAL LINE
- 0x7d } RIGHT CURLY BRACKET
- 0x7b ~ TILDE

Btw, Pages on Mac is not showing some fonts like TextEdit but I don't know if both are checking the same range of characters, I remember that Pages was ok with a smaller set like (a-zA-Z0-9) but I have to check to be sure.

**Comment by fdb** [comment]
@Jolg42 thanks for checking! So it's just a matter of including those characters? I'll try adding some more characters to the Pyramid test font and see if I can get it to display in Font Book and TextEdit.

**Comment by Jolg42** [comment]
@fdb Yes! apparently adding the complete set of Basic Latin characters is working :)
Here is the file I used to generate it -> https://gist.github.com/Jolg42/136042df0ea8366b01bf1712ea7a8926

**Comment by fdb** [comment]
After more testing it turns out the required set is .notdef, A-Z, a-z, 0-9 and space. I've updated the `generate-font-node` example and now it appears in TextEdit. Awesome!

**Comment by moyogo** [comment]
This doesn’t sound right. There are fonts without those glyphs working fine on OS X. Maybe the Mac cmap subtable should not be in the cmap when those characters are not in the font instead?

**Comment by fdb** [comment]
@moyogo the test font was working fine on OS X as well, only it's not showing in the TextEdit menu:

![screen-shot-2016-06-29-at-16 00 53](https://cloud.githubusercontent.com/assets/8477/16454900/ccc764ce-3e12-11e6-9e47-1106df2c2e8d.png)

By adding the characters, OS X detected it as Latin and showed it in the menu.

I don't really understand your comment. OpenType.js only generates the platform 3, encoding 1 table, so there is no Mac (platform Id 1) cmap table.

**Comment by moyogo** [comment]
@fdb You’re right. I should have checked first, those fonts I mentioned trigger the same issue actually.

**Comment by fdb** [comment]
@moyogo No problem 😄

**Comment by Jolg42** [comment]
@fdb nice to know! 👍 So .notdef, A-Z, a-z, 0-9 and space, but I looked at your commit & you added a period too, is it required too for a "full" font?

**Comment by fdb** [comment]
No the period is not required — I tested it without. It's just something I wanted to add because it's so frequently used.
