### ISSUE TITLE
encode.INDEX doesn't seem to properly evaluate encoder for some offset size

### ISSUE THREAD

**Issue by FranzPoize** [nodebox/opentype.js#202]
Hi,

Here is a string index content that when feeded to the encode.INDEX function (in src/types.js) will trigger the following error `prototypo.js:2346 Uncaught Error: Byte value should be between 0 and 255.`

This is the json representation of the string index that trigger this bug:
```[{"name":"string_0","type":"STRING","value":"0.1.0"},{"name":"string_1","type":"STRING","value":"Prototypo Elzevir Regular"},{"name":"string_2","type":"STRING","value":"Prototypo Elzevir"},{"name":"string_3","type":"STRING","value":"Regular"},{"name":"string_4","type":"STRING","value":"A_cap"},{"name":"string_5","type":"STRING","value":"B_cap"},{"name":"string_6","type":"STRING","value":"C_cap"},{"name":"string_7","type":"STRING","value":"D_cap"},{"name":"string_8","type":"STRING","value":"E_cap"},{"name":"string_9","type":"STRING","value":"F_cap"},{"name":"string_10","type":"STRING","value":"G_cap"},{"name":"string_11","type":"STRING","value":"I_cap"},{"name":"string_12","type":"STRING","value":"J_cap"},{"name":"string_13","type":"STRING","value":"K_cap"},{"name":"string_14","type":"STRING","value":"L_cap"},{"name":"string_15","type":"STRING","value":"M_cap"},{"name":"string_16","type":"STRING","value":"N_cap"},{"name":"string_17","type":"STRING","value":"O_cap"},{"name":"string_18","type":"STRING","value":"Q_cap"},{"name":"string_19","type":"STRING","value":"R_cap"},{"name":"string_20","type":"STRING","value":"S_cap"},{"name":"string_21","type":"STRING","value":"T_cap"},{"name":"string_22","type":"STRING","value":"U_cap"},{"name":"string_23","type":"STRING","value":"V_cap"},{"name":"string_24","type":"STRING","value":"W_cap"},{"name":"string_25","type":"STRING","value":"X_cap"},{"name":"string_26","type":"STRING","value":"Y_cap"},{"name":"string_27","type":"STRING","value":"Z_cap"},{"name":"string_28","type":"STRING","value":"a"},{"name":"string_29","type":"STRING","value":"b"},{"name":"string_30","type":"STRING","value":"c"},{"name":"string_31","type":"STRING","value":"d"},{"name":"string_32","type":"STRING","value":"f"},{"name":"string_33","type":"STRING","value":"g"},{"name":"string_34","type":"STRING","value":"h"},{"name":"string_35","type":"STRING","value":"i"},{"name":"string_36","type":"STRING","value":"j"},{"name":"string_37","type":"STRING","value":"k"},{"name":"string_38","type":"STRING","value":"m"},{"name":"string_39","type":"STRING","value":"n"},{"name":"string_40","type":"STRING","value":"q"},{"name":"string_41","type":"STRING","value":"s"},{"name":"string_42","type":"STRING","value":"u"},{"name":"string_43","type":"STRING","value":"v"},{"name":"string_44","type":"STRING","value":"w"},{"name":"string_45","type":"STRING","value":"x"},{"name":"string_46","type":"STRING","value":"z"},{"name":"string_47","type":"STRING","value":"one"},{"name":"string_48","type":"STRING","value":"two"},{"name":"string_49","type":"STRING","value":"three"},{"name":"string_50","type":"STRING","value":"four"},{"name":"string_51","type":"STRING","value":"five"},{"name":"string_52","type":"STRING","value":"six"},{"name":"string_53","type":"STRING","value":"seven"},{"name":"string_54","type":"STRING","value":"eight"},{"name":"string_55","type":"STRING","value":"nine"},{"name":"string_56","type":"STRING","value":"zero"},{"name":"string_57","type":"STRING","value":"H_cap"},{"name":"string_58","type":"STRING","value":"e"},{"name":"string_59","type":"STRING","value":"l"},{"name":"string_60","type":"STRING","value":"space"},{"name":"string_61","type":"STRING","value":"P_cap"},{"name":"string_62","type":"STRING","value":"r"},{"name":"string_63","type":"STRING","value":"t"},{"name":"string_64","type":"STRING","value":"y"},{"name":"string_65","type":"STRING","value":"p"},{"name":"string_66","type":"STRING","value":"o"}]```

With this string index dataSize is 255 and that gives a offSize of 1 to but since the offsets array starts from 1 it gives an offset which is 256 and that cannot be encoded into a BYTE.

**Comment by Jolg42** [comment]
👍 We have the same bug, thanks for the fix! (https://github.com/nodebox/opentype.js/pull/203)

**Comment by Jolg42** [comment]
@fdb This issue can be closed, it was merged with PR #203 ;-)
