### ISSUE TITLE
Allow loading from buffer

### ISSUE THREAD

**Issue by strarsis** [nodebox/opentype.js#208]
It can be helpful for some applications to let them load a font in opentype.js by passing a buffer.

**Comment by fdb** [comment]
Actually, you can. It's mentioned in the README:

    var font = opentype.parse(myBuffer);

myBuffer should be an [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer).

**Comment by strarsis** [comment]
Thanks!
