### ISSUE TITLE
fontMatrix

### ISSUE THREAD

**Issue by asmer** [nodebox/opentype.js#216]
Hello.

now I'm working on PostScript implementation for JS (something like pdf.js) and PS font subsystem very similar to opentype. I need some way to set fontMatrix, which generated inside of PostScript files. Any way to do this? I can try to fork and change code for that, but, probably you can offer some best way for that.

Thanks

**Comment by Jolg42** [comment]
Hi @asmer 

Right now the values of the fontMatrix are based on the font’s unitsPerEm.

So if you want to play with it you can hardcode it or add an `options.fontMatrix` here
https://github.com/nodebox/opentype.js/blob/2cb33b16078785fbb1551e812b5e7877c6dbb734/src/tables/cff.js#L1060

and the options input is here for this function https://github.com/nodebox/opentype.js/blob/2cb33b16078785fbb1551e812b5e7877c6dbb734/src/tables/sfnt.js#L293
