### ISSUE TITLE
Bump npm version

### ISSUE THREAD

**Issue by dfcreative** [nodebox/opentype.js#217]
Hi!
First off thanks for the awesome project, I use it in [wavefont](https://github.com/dfcreative/wavefont) for generating a font for rendering data.

There is a very required feature #194, which is not in @0.6.4 yet, therefore the request - could you add `Substitution` class to main `opentype` object and bump npm version?

Thanks!

**Comment by Jolg42** [comment]
Hi @dfcreative 

0.6.5 is on npm https://www.npmjs.com/package/opentype.js 😉
