### ISSUE TITLE
Add Support for Word Spacing / Letter Spacing

### ISSUE THREAD

**Issue by lachmanski** [nodebox/opentype.js#220]
Can you add support for [SVG word-spacing](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/word-spacing) and [SVG letter-spacing](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/letter-spacing)?

Word spacing could be useful for text justification purposes. Interestingly, the default [HTML word-spacing](http://www.w3schools.com/cssref/pr_text_word-spacing.asp) is 0.25 ems. This can be verified by comparing text between a `<p>` element and an opentype.js `<canvas>` element. Chrome ignores the font's internal spacing.

HTML Letter-spacing is added or subtracted between every characters in a string of text. Fortunately in this case it seems to supplement kerning rather than replace it. Letter Spacing is usually declared in ems. Graphics Software uses the term Tracking, and [multiplies the ems by 1000](http://stackoverflow.com/a/36612356/6465140) to avoid working in decimals.

I submitted a [PR for letter spacing / tracking](https://github.com/nodebox/opentype.js/pull/219). I'm not sure how to implement word spacing.

**Comment by fdb** [comment]
I noticed you added the issue to opentype-layout as well. Maybe that's a better place than here.

**Comment by Jolg42** [comment]
@fdb It's what I was thinking too
