### ISSUE TITLE
Remove planned ligature support from readme.

### ISSUE THREAD

**Issue by mrapogee** [nodebox/opentype.js#230]
According to #96, ligature support exists, correct? In the readme, it says ligatures are planned.

**Comment by fpirsch** [comment]
There is some ligature support indeed. Ligature data is read from and written to font files. The thing is, this data is not yet used for rendering.
Still, the readme could be updated to reflect this :-)

**Comment by mrapogee** [comment]
Ah, I see. :+:

Do you know what it take to support ligature rendering? I don't see an open issue for this.

**Comment by Jolg42** [comment]
Hi @mrapogee 

I just opnened the issue https://github.com/nodebox/opentype.js/issues/236 for ligatures rendering 😃 

Feel free to contribute!
