### ISSUE TITLE
Add ligature rendering in canvas

### ISSUE THREAD

**Issue by Jolg42** [nodebox/opentype.js#236]
Ligatures are supported but not rendered in canvas right now.

We will need to
- [ ] Add a ligature boolean for [GlyphRenderOptions](https://github.com/nodebox/opentype.js/blob/master/src/font.js#L206)
- [ ] Check all types of ligatures for a given string (maybe only a subset or the active ones for the first version?)
- [ ] Render the ligature in canvas
- [ ] Other modifications?

**Comment by fpirsch** [comment]
I'm on it ;-)
