### ISSUE TITLE
Unsupported kern table version (Anton font)

### ISSUE THREAD

**Issue by caub** [nodebox/opentype.js#244]
```
Error: Unsupported kern table version.
    at Object.exports.fail (opentype.js:402)
    at Object.exports.argument (opentype.js:409)
    at Object.parseKernTable [as parse] (opentype.js:6015)
    at Object.parseBuffer [as parse] (opentype.js:2227)
    at fetch.then.then.buf ((index):53)
```

https://jsfiddle.net/crl/2o3sfhrg/

This error happens for Coda, Didact Gothic font too

**Comment by adamgamble** [comment]
I just came here to report this as well. Any ideas?

**Comment by fdb** [comment]
The `kern` table is version 1; we only support version 0. The implementation is based on the Windows documentation. Apple's documentation does list the newer format, but we have no implementation for it yet.

**Comment by fdb** [comment]
Okay, I just pushed version 0.6.7 that has support for fonts like Anton, that only have a Mac-like `kern` table. Not all subtable versions are supported; but at least it shouldn't crash.
