### ISSUE TITLE
TypeError: subtables[i] is not a function at table.getKerningValue

### ISSUE THREAD

**Issue by caub** [nodebox/opentype.js#245]
```
TypeError: subtables[i] is not a function
    at table.getKerningValue (VM218 opentype.js:5536)
    at Font.getKerningValue (VM218 opentype.js:914)
    at fetch.then.then.then.font (VM491:60)
```

https://jsfiddle.net/crl/2o3sfhrg/1/

This error happens for Ek Mukta, Cardo, Cousine, Bungee Inline, Jomhuria,  Aref Ruqaa, NTR, Gurajada, Buenard fonts too

**Comment by fpirsch** [comment]
Hi,
thanks for the report. It happens with Raleway too. I will fix this soon.
