### ISSUE TITLE
TypeError is thrown when layout.scripts is null in 0.6.9

### ISSUE THREAD

**Issue by lozen130** [nodebox/opentype.js#254]
TypeError: Cannot read property ‘length’ of undefined

```
at Object.Layout.getDefaultScriptName
(.../node_modules/opentype.js/src/layout.js:111:43)
at Font.stringToGlyphs
(.../node_modules/opentype.js/src/font.js:155:58)
```

``` 
   /**
     * Returns the best bet for a script name.
     * Returns 'DFLT' if it exists.
     * If not, returns 'latn' if it exists.
     * If neither exist, returns undefined.
     */
    getDefaultScriptName: function() {
        var layout = this.getTable();
        if (!layout) { return; }
        var hasLatn = false;
        for (var i = 0; i < layout.scripts.length; i++) {
            var name = layout.scripts[i].tag;
            if (name === 'DFLT') return name;
            if (name === 'latn') hasLatn = true;
        }
        if (hasLatn) return 'latn';
    },
```

**Comment by fpirsch** [comment]
Hi @lozen130,
I will fix this. Can you provide an example font ? I suspect the problem could be deeper.

**Comment by malublu** [comment]
I have no exception but i port this lib to an other language and found something like this:
https://thepasteb.in/p/wjhzcKnWJvxw0u6

So it could be fix if you precheck if the table has scripts or add to os2 a simple empty script body.

**Comment by fpirsch** [comment]
@malublu This issue is only for layout tables GPOS and GSUB

**Comment by malublu** [comment]
@fpirsch Ah okay.
Currently i find it difficult to read your lib and port all the code, sorry for my mistake.
Because sometimes you have Objects like a table and sometimes you are only use plainobjects.
And sometimes the Objects get a field dynamicly (like the scripts field).

**Comment by antonytse** [comment]
@fpirsch The problem (layout.scripts is undefined) can be reproduced by using League Gothic Regular which can be downloaded from Font Squirrel.

https://www.fontsquirrel.com/fonts/league-gothic

**Comment by TeisD** [comment]
I fixed this in my application by modifying `getTable` in layout.js like this:

```js
   /**
     * Get or create the Layout table (GSUB, GPOS etc).
     * @param  {boolean} create - Whether to create a new one.
     * @return {Object} The GSUB or GPOS table.
     */
    getTable: function(create) {
        console.log(this.tableName);
        let layout = this.font.tables[this.tableName];
        if ((!layout && create) || layout.scripts === undefined) {
            console.log("creating default table");
            layout = this.font.tables[this.tableName] = this.createDefaultTable();
        }
        return layout;
    },
```

It didn't break anything else so far, but it's not really a solution as it doesn't address the underlying problem (which I couldn't locate).

Anyway, it might be useful as a reference to anyone looking for a quick fix.

**Comment by aparrish** [comment]
having this exact same problem with this exact same font!

**Comment by lojjic** [comment]
A couple more fonts that trigger this exception - not necessarily the same root cause but the same symptom at least:

Cutive Mono: https://fonts.gstatic.com/s/cutivemono/v6/m8JWjfRfY7WVjVi2E-K9H6RCTmg.woff
Gabriela: https://fonts.gstatic.com/s/gabriela/v6/qkBWXvsO6sreR8E-b8m5xL0.woff

**Comment by Jolg42** [comment]
It should be fixed in master (I need to build the dist files) thanks to @fpirsch 👍
