### ISSUE TITLE
Deformed glyphs

### ISSUE THREAD

**Issue by greegus** [nodebox/opentype.js#255]
Some glyphs have been parsed with misplaced point at the start/end of the bezier curve, and so the glyph appears to be deformed. This mostly occurs when the closing point is on the curve (not in the corner) typically on `O`, or `0` glyphs, but also some others (depending on the font).

Here is an example of such misplacement within `O` glyph in `Futura Condensed ExtraBold` font. The character on the left is outlined in Adobe Illustrator. On the right there is this character processed by opentype.js using Glyph Inspector (http://opentype.js.org/glyph-inspector.html) with same font loaded.

![image](https://cloud.githubusercontent.com/assets/11144945/22111894/50d175ea-de61-11e6-8fb2-e6c3aca4bc7f.png)

**Comment by cdave1** [comment]
[Here's a fairly rough patch I wrote to fix this](https://github.com/cdave1/opentype.js/commit/3db0fcbbb7cf77984eec14bbcd381986c5dc6346), since I found similar problems with a lot of different fonts and it was driving me crazy.

![text3386](https://cloud.githubusercontent.com/assets/157290/22684752/939a35c6-ed82-11e6-9330-e2e3aef75d1b.png)

**Comment by fpirsch** [comment]
Thanks @greegus and @cdave1,
which version of Futura Condensed ExtraBold are you using ? I can't reproduce the problem with version 001.003 in OTF.

**Comment by greegus** [comment]
@fpirsch I'm using 006.000 TrueType

**Comment by fpirsch** [comment]
Ah OK I see it now. Thanks @greegus !

**Comment by Jolg42** [comment]
I can't find the exact Futura version cited before, any link or maybe another font with the same problem?

**Comment by greegus** [comment]
@Jolg42 [futura-006.000.zip](https://github.com/nodebox/opentype.js/files/877914/futura-006.000.zip)

**Comment by Jolg42** [comment]
@greegus Thank you! Indeed I have the same problem, I'm gonna check that :)

**Comment by Jolg42** [comment]
@greegus The fix is live on http://opentype.js.org/glyph-inspector.html Thanks to @cdave1 for the fix 😉
