### ISSUE TITLE
How does chrome make it more crisp / fi Glyph missing

### ISSUE THREAD

**Issue by axkibe** [nodebox/opentype.js#258]
First thank you for opentype.js. It look wonderful.

Below is a comparison of canvas.fillText() [left] vs. opentype.draw() [right]

![screenshot](https://cloud.githubusercontent.com/assets/495407/23071013/401ec832-f52d-11e6-95f1-48fec086c60f.png)

Unfortunally the left one looks way more crisp. Any Idea how Chrome does this? Does it snap/align the gylphs (in some cases they look a little displayed too)? I tried around snapping the points like the demo on a 1-distance grid, but it just gets worse.

In this case the fonts are drawn to an alpha enabled canvas, so there is no RGB-subpixel antialiasing going on anyway.

PS: Chrome seems to have kerning disabled by default, opentype does a much better job on 'Ts' here.

However, fi as ligature seems not to work in opentype.js case.

Both versions use DejaVuSans version 2.37, the same ttf file loaded via google webfont and via opentype.

I also tried offseting the base x/y coord with 0.5, similar impression, a little more sluggish.

**Comment by axkibe** [comment]
BTW: The issue with canvas.fillText() is, and I looked into opentype, the first one doesn't scale geometrically well. For example a string like 'ooooooooooooooooooooo' drastically changes it's width compared to normal text for different font sizes.

Thats why guess, chrome somehow snaps each glyph to the pixel grid?

**Comment by fdb** [comment]
This is because `canvas.fillText()` uses [font hinting](https://en.wikipedia.org/wiki/Font_hinting). This uses extra information, stored in the font, to fit the stems to a pixel grid.

Because OpenType.js converts the font to Bézier paths, we no longer have this information, so it's impossible to render them in the same way.

**Comment by axkibe** [comment]
I looked into it, font hinting is "nothing else" than an extremly sophisticated way to align the points to the pixelgrid, before turning them into Béziers, so it is very possible with OpenType.js. I'm looking into it implementing a javascript font hinting interpreter.

**Comment by fdb** [comment]
@axkibe that would be cool — if we could do this before turning them into Béziers, then I'm all ears.
