### ISSUE TITLE
font.getPath() : letters not well positionned

### ISSUE THREAD

**Issue by microSoftware** [nodebox/opentype.js#261]
Hi, I guess it's a normal behavior but I don't understand something.
When I want to get the path of a specific word or letter. I need to specify an x and y.

var PathObject = font.getPath(word, **posx**, **posy**);

And when I display the path in a browser I got this :
![screen shot 2017-03-24 at 11 42 46](https://cloud.githubusercontent.com/assets/3915272/24275893/0838d122-1087-11e7-980f-5a5a4f22a3cc.png)

If I tried to find the good x and y I got something well positioned...
![screen shot 2017-03-24 at 11 46 07](https://cloud.githubusercontent.com/assets/3915272/24275963/83436350-1087-11e7-9296-cf0facea5d75.png)

But then If I want to get the path of another word I have to find again the good x and y. Is there a way to guess the x and y for a font or any tips to make is easier to find it 

I'm sure it's something I don't get but if someone can help me figure it out. I would really appreciate it.
Thank you

**Comment by Jolg42** [comment]
Hi @microSoftware 
I don't know if I can help on that subject, but did you find a solution?

**Comment by fdb** [comment]
This seems like an issue with the baseline of the text?
