### ISSUE TITLE
Scrambled rendering with NotoSansTC-Regular.otf

### ISSUE THREAD

**Issue by edouard-lopez** [nodebox/opentype.js#273]
**related:** #243, googlei18n/noto-cjk#81

I met rendering problems when using `text-to-svg` (shrhdk/text-to-svg#22, shrhdk/text-to-svg#23) with the `NotoSansTC-Regular.otf`.
Drilling down it appears `text-to-svg` is based on `opentype.js`.

### Expected
This is for reference, I find that `DroidSansFallbackFull.ttf` worked fine.

| key | value |
| --- | --- |
| font | DroidSansFallbackFull.ttf | 
| text | 㐅㐆丰wǔyǐnfēng |

![DroidSansFallbackFull.ttf using opentype.js](https://cloud.githubusercontent.com/assets/1212392/24569040/a34f7e80-1664-11e7-9466-60f8cfdd1f37.png)

### Actual (with NotoSans)

I tested on [opentype.js online demo](http://opentype.js.org/) and the result is scramble too (see below):

| key | value |
| --- | --- |
| font | [NotoSansTC-Regular.otf](https://github.com/googlei18n/noto-cjk/blob/master/NotoSansTC-Regular.otf) | 
| text | 㐅㐆丰wǔyǐnfēng

![NotoSansTC-Regular.otf using opentype.js](https://cloud.githubusercontent.com/assets/1212392/24568749/7277234a-1663-11e7-8007-dcfb106bb7f2.png)

**Comment by brawer** [comment]
The same font renders fine with [FontView](https://github.com/googlei18n/fontview) so this looks like a problem of OpenType.js.

**Comment by edouard-lopez** [comment]
_Noto Serif_ has been [released on April 2017](https://www.wired.com/2017/04/googles-new-font-honors-ancient-type-traditions/) but still has the issue. From [googlei18n/noto-cjk#81](https://github.com/googlei18n/noto-cjk/issues/81#issuecomment-292936624) the issue come from OpenType.js.

Could you give some feedback?

**Comment by brawer** [comment]
Same for Noto Serif — the font renders fine with FontView (which is just a GUI wrapper around HarfBuzz and FreeType), so this looks like a bug in OpenType.js. If someone figures out what exactly is triggering this bug, would you mind contributing a test font (with just 2 glyphs) to Unicode? If you send a pull request to [Unicode’s text rendering test suite](https://github.com/unicode-org/text-rendering-tests) and accept Unicode’s contributor license agreement, I’ll gladly add a test case that uses your font. By doing this, you will help to make all OpenType implementations towards more compliant with the spec.

![image](https://cloud.githubusercontent.com/assets/1527880/24862693/f16a52b6-1dfd-11e7-8f2b-454e8cc5abd7.png)

**Comment by fdb** [comment]
It seems the `advanceWidth` values are messed up. I'll try to figure out why.

**Comment by fdb** [comment]
It seems like this is a CID-keyed font, which we do not yet have support for. I'll see what I can do.

**Comment by brawer** [comment]
Indeed, OpenType.js runs into the same problem with [this test font](https://github.com/unicode-org/text-rendering-tests/raw/master/fonts/FDArrayTest257.otf):

![image](https://cloud.githubusercontent.com/assets/1527880/24867472/967fe482-1e0d-11e7-866d-325543e690ee.png)

Instead, it should look [like this](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/FreeStack.html#CFF-1).

**Comment by fdb** [comment]
We now parse CID-keyed fonts correctly!

![screen shot 2017-04-25 at 14 29 07](https://cloud.githubusercontent.com/assets/8477/25385203/8d14d4c2-29c3-11e7-8eef-79fcd88f2b79.png)

The new version 0.7.0 includes the fix (with a big thanks to @tshinnic for the initial implementation).
