### ISSUE TITLE
Discrepancy in tableEntries

### ISSUE THREAD

**Issue by mudcube** [nodebox/opentype.js#275]
An error is thrown in `parseBuffer(...)` when calling `parseShortList(...)` due to a discrepancy in how `parseOpenTypeTableEntries(...)` & `parseWOFFTableEntries(...)` returns values. This ends up throwing an error when parsing any WOFF font that includes a `cvt` table.

More specifically, `parseShortList(tableEntry.length / 2)` is expecting `tableEntry` to have a `length`, but the WOFF parser only returns the values `compressedLength` and `originalLength` so `tableEntry.length` ends up equalling `undefined`. This ends up throwing an error when `new Array(count)` is being called in `parseShortList(...)`

Towards a solution, which of these two values (`compressedLength` and `originalLength`) should be being passed to parseShortList(...) as `length`?

**Comment by fdb** [comment]
I noticed this too yesterday, with parsing the `cvt ` table. It needs to be passed the `originalLength`. Better would be to rename "originalLength" to "length" when parsing tableEntries.

Is this something you want to look at?

**Comment by darionco** [comment]
Just making some noise, can we get PR #295 merged to fix this issue? Thanks!
