### ISSUE TITLE
Support TrueType fonts

### ISSUE THREAD

**Issue by brawer** [nodebox/opentype.js#278]
Currently, OpenType.js cannot open TrueType fonts such as [Zycon](https://github.com/unicode-org/text-rendering-tests/raw/master/fonts/Zycon.ttf); it fails with “Error: Unsupported OpenType signature true”.

**Comment by Jolg42** [comment]
@brawer You're right ;)
> OpenType fonts that contain TrueType outlines should use the value of 0x00010000 for the sfntVersion.

> NOTE: The Apple specification for TrueType fonts allows for 'true' and 'typ1' for sfnt version. These version tags should not be used for fonts which contain OpenType tables.`

**Comment by Jolg42** [comment]
Fixed in master!
