### ISSUE TITLE
Add code quality tools

### ISSUE THREAD

**Issue by fdb** [nodebox/opentype.js#28]
As the project grows it is important that the quality of the code remains high: no regressions should be introduced and the overal coding style remains consistent. 

For tests, set up a testing suite that runs automatically and catches regressions with built-in fonts.

For code consistency, set up JSHint. This should be integrated in a `npm test` task, and be checked in continuous integration (so it can automatically test pull requests).

In addition, also mention these guidelines in a [CONTRIBUTING.md file](https://github.com/blog/1184-contributing-guidelines).

**Comment by fdb** [comment]
We now run JSCS together with JSHint.

**Comment by oriSomething** [comment]
hey, how about adding tools like `mocha` and `chai`, and then starting making unit tests when new features added? :)

**Comment by fdb** [comment]
@oriSomething You're right! This is long overdue. 

This reason why we haven't done this is because it all starts with bytes, and making unit tests that say: "here's this unreadable byte-stream, will this match up with this data structure" makes them defeat the purpose, I think.

It would be useful to catch regressions this way, though.

**Comment by oriSomething** [comment]
i totally understand you. i'm not a big fan of TDD in new projects, but at this time of the project it can start to be useful, and make adding new features much easier.
if it's not something that needed now, i can scaffold the base of having the ability to use unit testing easily, and after this we can add more and more tests with time. but it will be more like in 3-5 weeks 'til i can sit on it.
