### ISSUE TITLE
dist/opentype.js dist works, opentype.min.js fails to load font

### ISSUE THREAD

**Issue by valrus** [nodebox/opentype.js#293]
## Expected Behavior
I'm trying to load the League Gothic font downloadable on [this page](https://www.theleagueofmoveabletype.com/league-gothic), specifically either the leaguegothic-regular-webfont.ttf or LeagueGothic-Regular.otf files.

## Current Behavior
Using the current master of opentype.js ([this commit](https://github.com/nodebox/opentype.js/commit/6b9a2444663c5f584d18e203188167f5ae862723)), loading either font works fine.

However, using opentype.min.js (same commit), I get the following error in the `opentype.load` callback:
```
Could not load font: TypeError: _font2.default is not a constructor
```

## Steps to Reproduce (for bugs)
1. Download League Gothic from https://www.theleagueofmoveabletype.com/league-gothic
2. Place either the .otf or .ttf version of the Regular font in a location accessible to the server
3. Load opentype.min.js: `<script src="static/js/text/opentype.min.js"></script>`
4. Load the font as shown in "[Loading a font](https://github.com/nodebox/opentype.js#api)" (the path I used was 'static/fonts/leaguegothic/leaguegothic-regular-webfont.ttf')

## Context
This isn't too killer as my project requires loading an mp3 too, so an extra 150K or so won't be a dealbreaker, but it's weird that minification seems to have broken something.

## Your Environment

* Version used: master (https://github.com/nodebox/opentype.min.js/commit/6b9a2444663c5f584d18e203188167f5ae862723)
* Font used: [League Gothic](https://www.theleagueofmoveabletype.com/league-gothic)
* Browser Name and version: Firefox 53.0.2
* Operating System and version (desktop or mobile): macOS 10.12.5, desktop
* Link to your project: https://github.com/valrus/auto-lyric-music-video (but it doesn't include my attempt to use this yet)

**Comment by fdb** [comment]
Thanks for the report. I'll check it out.

**Comment by fdb** [comment]
It seems to do with the usage of the new ES6-style import/exports we wrote. Apparently the minifier is not too happy with them.

**Comment by fdb** [comment]
Apparently [UglifyJS doesn't work with ES6 modules](https://github.com/TrySound/rollup-plugin-uglify#warning). 

I'll check if using the uglify-es version helps.

**Comment by fdb** [comment]
Short answer: no it doesn't :-)

I know just use the following command line to produce the minified build:

    uglifyjs ./dist/opentype.js > ./dist/opentype.min.js

This seems to avoid the issues with ES2015, since Uglify only sees the babelified code.
