### ISSUE TITLE
Fail to load most WOFF font

### ISSUE THREAD

**Issue by karltaidev** [nodebox/opentype.js#300]
Most WOFF fonts failed to load with error:
```
RangeError: Invalid array length
    at Parser.parseShortList (opentype.js:5853)
    at parseBuffer (opentype.js:5450)
    at opentype.js:5597
    at XMLHttpRequest.request.onload (opentype.js:5290)
```

Successfully loaded WOFF: https://fonts.gstatic.com/s/dancingscript/v8/DK0eTGXiZjN6yA8zAEyM2bDH3ri20rYH10B2w3wbVeU.woff

Failed WOFF: 
https://fonts.gstatic.com/s/dancingscript/v8/DK0eTGXiZjN6yA8zAEyM2VhlQWQpSCpzb2Peu3I-Q34.woff

They are the same web font from google web font. I saved the url at different time. The same error occur when using the WOFF font converted from tff.

**Comment by fdb** [comment]
Both URLs work for me in the online viewer. Do you have a static font file I could test?
![screen shot 2017-07-24 at 14 10 53](https://user-images.githubusercontent.com/8477/28522839-ee62cde0-7079-11e7-8eac-75be8acb94c9.png)

**Comment by karltaidev** [comment]
Thanks. The issue has been resolved after updating the js file.
