### ISSUE TITLE
'Font could not be loaded' error on Android devices

### ISSUE THREAD

**Issue by maoamid** [nodebox/opentype.js#301]
When used in a cordova app environment (hybrid or not), the font cannot be loaded on Android devices  

## Expected Behavior
the font should be loaded, using `loadFromUrl` function

## Current Behavior
error: Font could not be loaded

## Possible Solution
```javascript
function loadFromUrl(url, callback) {
    var request = new XMLHttpRequest();
    request.open('get', url, true);
    request.responseType = 'arraybuffer';
    request.onload = function() {
        if (request.status !== 200) {
            return callback('Font could not be loaded: ' + request.statusText);
        }

        return callback(null, request.response);
    };

    request.onerror = function () {
        callback('Font could not be loaded');
    };

    request.send();
}
```

**request.onload()** was not running because `request.open('get', url, true);` should be replaced with` request.open('GET', url, true);`

## Your Environment
Android apps build on:
- Tabris.js
- Cordova based environment
- Hybrid apps without using node 'fs' request
iOS devices not affected

**Comment by Jolg42** [comment]
Hi @maoamid 
Your solution looks good, from the specification `GET` should be in uppercase.
If you add a PR I will merge it asap ;)

**Comment by Jolg42** [comment]
Merged! Do you need a new release?

**Comment by maoamid** [comment]
Great, 
I don't need a new release, just for that. Have a great day.
