### ISSUE TITLE
Strange fontsize for different fonts

### ISSUE THREAD

**Issue by elenaramirez** [nodebox/opentype.js#304]
Hi folks! I'm trying the glyph inspector feature of this plugin, but i've an strange behavior with different fonts. 

Some of them are render very small comparing with other ones, as you can see in the follow screenshots. 

https://www.dropbox.com/s/8xukyzfjiv72q9a/Captura%20de%20pantalla%202017-09-05%2009.59.39.png?dl=0
https://www.dropbox.com/s/rs5y93ed9f4for4/Captura%20de%20pantalla%202017-09-05%2009.59.32.png?dl=0

For some reason the first one is render bigger than the second one .
For i can see the ymax and ymin are different in both of them, but it isn't declared in none of the fonts. So what could be the specific data in the font table that is making this wrong? Or maybe is it a bug of the code?

Can anyone help me to find the solution here?

Thank you so much in advance!

**Comment by fdb** [comment]
The coordinates are taken directly from the font: 

- the size of the box is unitsPerEM (the first is a CFF font, so probably 1000 units).
- the baseline is at Y position 0.
- the ascender and descender are defined in the font's [`hhea`](https://www.microsoft.com/typography/OTSPEC/hhea.htm) table.

Because the glyph inspector tries to show the whole box, it can scale the font unnaturally, so it might be that it doesn't accurately represents the actual size of the letters. Do they render in different font sizes on the OpenType.js homepage as well?

**Comment by elenaramirez** [comment]
Hi fdb!

Thank you for your help. 

I've checked the metrics for the values you comment. In both cases unistsPerEM is 1000 units, and baseline at Y is set to 0. 

Checking the hhea table i've discovered something with the smaller font. 
In the bigger font the ascender/descender values are equal to yMax/yMin values, but in the smaller fonts are different. Could be this the reason for the problem?

https://www.dropbox.com/s/0ylzlzxy5x53gsn/Captura%20de%20pantalla%202017-09-06%2013.03.48.png?dl=0

Anyway in the homepage of OpenType.js the render for the smaller font are better than Glyph Inspector. 

https://www.dropbox.com/s/xt2k2metckzmldg/Captura%20de%20pantalla%202017-09-06%2012.55.45.png?dl=0

Why is better in this case?

Thank you again and have a nice day!!

**Comment by elenaramirez** [comment]
Anyone there that can help me? I'm still struggle with this.

**Comment by fpirsch** [comment]
Can't access the dropbox links.
I had the same behavior with Zilla-Slab which has a very wide glyph at the end.
The glyph scaling is computed for the font so that every glyph can fit in the box with the same scale factor.
So if your font has even one very big glyph, everything will be scaled down.

**Comment by Jolg42** [comment]
Oh ok, and indeed the links are broken. Should I reopen that issue @fpirsch?

**Comment by fpirsch** [comment]
@Jolg42 it's not a bug, but maybe it could be improved. IMO it's important that all glyphs be shown in the inspector at the same scale. I don't really know how to handle those (rare) fonts which have some disproportionate glyphs.

**Comment by elenaramirez** [comment]
Yes, sorry i needed some space at dropbox and deleted the pictures a while ago :(

Sometimes fonts has some ornaments that could create disproportionate glyphs as you say. And i understand about to keep the same scale for the glyphs, but maybe there is any way to control those glyphs that are over the average? And force them to scale up/down in order to fit in the average size?

It's just a thought but maybe it could help somehow.
