### ISSUE TITLE
Update Roboto used in demos

### ISSUE THREAD

**Issue by davelab6** [nodebox/opentype.js#310]
## Expected Behavior
The demos (eg https://opentype.js.org/font-inspector.html) use the latest and greatest version of Roboto

## Current Behavior
The demo's version is from 2011 :(

## Possible Solution
Update the file

**Comment by Jolg42** [comment]
New version was merged in master with https://github.com/nodebox/opentype.js/commit/964a82b41f05ac275be785b689fceb856de28ac1
