### ISSUE TITLE
Draw a single glyph in other color.

### ISSUE THREAD

**Issue by CrzDog** [nodebox/opentype.js#316]
## Summary
Now I can not find a way to draw a single glyph by different color.

## Expected Behavior
The function 'Glyph.draw(ctx, x, y, fontSize, options)' in glyph.js should use ctx.fillStyle setted by user instead of the default fill value ('black').

## Current Behavior
Although I set ctx.fillStyle to other values except 'black' before  I call Glyph.draw(ctx, x, y, fontSize, options) to draw a single glyph, the glyph will still be rendered in black color.

## Possible Solution
change the function Path.draw(ctx) in path.js.
when user have set ctx.fillStyle or ctx.strokeStyle to custom value,
use the custom value to draw path.

**Comment by axkibe** [comment]
As you can see here, it uses the path.fill attribute:
https://github.com/nodebox/opentype.js/blob/dff36fbc45d0913d7865abf94fb3141ddc8a4d7c/src/path.js#L219

So you can call call Glyph.getPath, change the fill attribute and then call path.draw(ctx);

IMHO it's not a pretty API but it works.

**Comment by CrzDog** [comment]
thanks for your comment, it works.

**Comment by benoitwimart** [comment]
I don't find how to do this with `font.draw()` :(
