### ISSUE TITLE
Any way to get correct x-height of a font?

### ISSUE THREAD

**Issue by orklann** [nodebox/opentype.js#317]
`glyph-inspector.html` show how to get some metrics of a font like ascender, descender, etc, but I can not figure out how to get x-height in a font, dose `opentype.js` support this?

**Comment by axkibe** [comment]
I'm using this for capheight. I suppose something similar can be done for x-height. I don't remember why I ignore the value given in the font object, I suppose it had reasons.

```
function getCapHeight( font )
{
    const chars = 'HIKLEFJMNTZBDPRAGOQSUVWXY';

    for( let a = 0, al = chars.length; a < al; a++ )
    {
        const idx = font.charToGlyphIndex( chars[ a ] );

        if( idx < 0 ) continue;

        return font.glyphs.get( idx ).getMetrics( ).yMax;
    }
}
```

in fact in sfnt.js you'll find this:
sxHeight: metricsForChar(font, 'xyvw', {yMax: Math.round(globals.ascender / 2)}).yMax,

Sorry I can't give you a full answer, only some hints.

**Comment by orklann** [comment]
@axkibe I am not want to measuring any glyph to get the x-height, but thanks for your sample code.

I just found `tables.os2.sxHeight` is available if the font's `tables.os2.version >= 2`. So I know how to get x-height now by reading the source code.

**Comment by axkibe** [comment]
Okay, maybe you might also want to put in the fallback workaround with measuring it, if it isn't available, but maybe you don't have to, if you know all the fonts you are using have this table entry filled.

**Comment by ming-codes** [comment]
Hm, this may sounds obvious but..

Why not just grab the `x` glyph and compute the difference between min and max of y in the contours list? I think this is the closest estimate of the x-height.
