### ISSUE TITLE
Cannot render codepoints above U+FFFF in CFF

### ISSUE THREAD

**Issue by brawer** [nodebox/opentype.js#327]
When rendering CFF fonts, OpenType.js currently fails to handle codepoints about U+FFFF.  See test cases [CFF-1](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/OpenType.js.html#CFF-1) and [CFF-2](https://rawgit.com/unicode-org/text-rendering-tests/master/reports/OpenType.js.html#CFF-2). To reproduce, run the [test suite](https://github.com/unicode-org/text-rendering-tests).

**Comment by antonytse** [comment]
I have just tried to fix this in #331, which should pass the test cases CFF-1 and CFF-2.

**Comment by fpirsch** [comment]
Closed through #338
