### ISSUE TITLE
The toPathData always return the 'L' path twice

### ISSUE THREAD

**Issue by weixiongmei** [nodebox/opentype.js#328]
When calling the getPath().toPathData(), the 'L' paths are always added twice to the path data. Such as the sample data below:
M 0.85 12.03
L 0.85 8.10
L 0.85 8.10
Q 0.70 8.06 0.57 7.99
L 0.57 7.99
L 0.57 7.99
Q 0.44 7.93 0.33 7.84
L 0.33 7.84
L 0.33 7.84
Q 0.21 7.74 0.14 7.62
L 0.14 7.62
L 0.14 7.62
Q 0.06 7.49 0.03 7.33
L 0.03 7.33
L 0.03 7.33
Q -0.08 6.95 0.16 6.59
L 0.16 6.59
L 0.16 6.59
Q 0.39 6.23 0.77 6.15
L 0.77 6.15
L 0.77 6.15
Q 1.15 6.04 1.52 6.28
L 1.52 6.28
L 1.52 6.28
Q 1.88 6.51 1.95 6.90
L 1.95 6.90
L 1.95 6.90
Q 1.99 7.04 2.00 7.19
L 2.00 7.19
L 2.00 7.19
Q 2.00 7.33 1.98 7.52
L 1.98 7.52
L 1.98 7.52
Q 1.96 7.71 1.95 7.80
L 1.95 7.80
L 1.95 7.80
Q 1.93 7.89 1.88 8.13
L 1.88 8.13
L 1.88 8.13
Q 1.83 8.37 1.82 8.42
L 1.82 8.42
L 1.82 8.42
Q 1.51 9.79 0.85 12.03
L 0.85 12.03
Z

Browser: Chrome
System: Windows 10
Font: All .ttf fonts, i haven't try any other type of font, but every ttf font that i have, they have the same issue...

**Comment by Jolg42** [comment]
Hi!ny font that has this probem?
Could you tell us what version of OpenType.js do you have? And a font that has this problem?

**Comment by weixiongmei** [comment]
Hi,
Any ttf font file you could found on the windows Fonts folder, version V0.8.0 .... But i got the problem fixed already...
The working code is changed to below:

function getPath(points) {
    var p = new Path();
    if (!points) {
        return p;
    }

    var contours = getContours(points);

    for (var contourIndex = 0; contourIndex < contours.length; ++contourIndex) {
        var contour = contours[contourIndex];

        var prev = null;
        var curr = contour[contour.length - 1];
        var next = contour[0];

        if (curr.onCurve) {
            p.moveTo(curr.x, curr.y);
        } else {
            if (next.onCurve) {
                p.moveTo(next.x, next.y);
            } else {
                // If both first and last points are off-curve, start at their middle.
                var start = {x: (curr.x + next.x) * 0.5, y: (curr.y + next.y) * 0.5};
                p.moveTo(start.x, start.y);
            }
        }

        for (var i = 0; i < contour.length; ++i) {
            prev = curr;
            curr = next;
            next = contour[(i + 1) % contour.length];

            if (curr.onCurve) {
                // This is a straight line.
                p.lineTo(curr.x, curr.y);
            } else {
                var prev2 = prev;
                var next2 = next;

                if (!prev.onCurve) {
                    prev2 = { x: (curr.x + prev.x) * 0.5, y: (curr.y + prev.y) * 0.5 };
                    //p.lineTo(prev2.x, prev2.y);
                }

                if (!next.onCurve) {
                    next2 = { x: (curr.x + next.x) * 0.5, y: (curr.y + next.y) * 0.5 };
                }

                //p.lineTo(prev2.x, prev2.y);
                p.quadraticCurveTo(curr.x, curr.y, next2.x, next2.y);
            }
        }

        p.closePath();
    }
    return p;
}

**Comment by Jolg42** [comment]
What did you change exactly? It's not clear for me. (the 2 `//p.lineTo` maybe?)

**Comment by weixiongmei** [comment]
Yes, just 2 //p.lineTo, that's it.....

**Comment by Jolg42** [comment]
Indeed for `0` with Roboto-Black on master https://codepen.io/Jolg42/pen/MVGoGJ?editors=1100#0

It's fixed in master ;-)
