### ISSUE TITLE
Font.getKerningValue(leftGlyph, rightGlyph) seems broken in 0.8.0

### ISSUE THREAD

**Issue by ivarref** [nodebox/opentype.js#332]
## Current Behavior (0.8.0 only)
I would expect the following code
```javascript
var opentype = require('opentype.js');
var font = opentype.loadSync('fonts/Roboto-Black.ttf');
var glyphT = font.charToGlyph('T');
console.log(font.getKerningValue(glyphT, glyphT));
```
to output `16` on the console as it does in `0.7.3`. Instead it prints `0` in `0.8.0`.

## Steps to Reproduce
Paste the above snippet to `demo.js` in an folder containing `fonts/Roboto-Black.ttf`, then on the shell do
```bash
yarn add opentype.js@0.7.3 && node ./demo.js
yarn add opentype.js@0.8.0 && node ./demo.js
```
to see the difference in output.

Another way to reproduce this issue is to look at the generated path data:
```javascript
var opentype = require('opentype.js');
var font = opentype.loadSync('fonts/Roboto-Black.ttf');
var glyphT = font.charToGlyph('T');
var kerningValue = font.getKerningValue(glyphT, glyphT);

var fontSize = 72;
var fontScale = 1 / font.unitsPerEm * fontSize;

console.log("kerning value is:", kerningValue);

var xpos = (glyphT.advanceWidth+kerningValue)*fontScale;
var manualPath = glyphT.getPath().toPathData() + glyphT.getPath(xpos).toPathData();

if (manualPath === font.getPath("TT").toPathData()) {
  console.log("path is identical as expected");
} else {
  console.log("path mismatch");
}
```

Running this will produce `path mismatch` on `0.8.0`, but not on `0.7.3`.

## Your Environment
* Version used: 0.7.3 / 0.8.0
* Font used: Roboto-Black.ttf
* Node version: v9.8.0
* Operating System and version (desktop or mobile): OS X

**Comment by Jolg42** [comment]
Hi @ivarref 

Thanks for reporting that issue!

Actually the Roboto Black font was updated recently see https://github.com/nodebox/opentype.js/commits/master/fonts/Roboto-Black.ttf

Could you try to check if it's because of that update by trying your code on the 0.8.0 branch with the old version of Roboto Black?

**Comment by ivarref** [comment]
Hi, and thanks for the fast reply as well as a fine library! 

> Could you try to check if it's because of that update by trying your code on the 0.8.0 branch with the old version of Roboto Black?

Yes, this is correct, but only for `0.8.0`. The new Roboto Black works as expected on `0.7.3`.

## Setup
```bash
$ curl https://raw.githubusercontent.com/nodebox/opentype.js/0912c68552c22016c2436123aa71ca9b7db70fc0/fonts/Roboto-Black.ttf -o old.ttf
$ curl https://raw.githubusercontent.com/nodebox/opentype.js/af447e6c31bf64f340184005f504ec1cbf54af90/fonts/Roboto-Black.ttf -o new.ttf
```

## Code
```javascript
var opentype = require('opentype.js');

function showKerningValue(file) {
	var font = opentype.loadSync(file);
	var glyphT = font.charToGlyph('T');
	console.log("kerning value:", font.getKerningValue(glyphT, glyphT), "font:", file);
}

showKerningValue('./new.ttf');
showKerningValue('./old.ttf');
```

## Output
```bash
$ yarn add opentype.js@0.7.3 && node ./demo.js
kerning value: 16 font: ./new.ttf
kerning value: 16 font: ./old.ttf

$ yarn add opentype.js@0.8.0 && node ./demo.js
kerning value: 0 font: ./new.ttf
kerning value: 16 font: ./old.ttf
```

**Comment by ivarref** [comment]
Let me know if you need more details.

**Comment by Jolg42** [comment]
Thanks @ivarref for testing, it looks like there is indeed an issue.
But not sure if I will have the time to dig into this in the next few days though...

**Comment by fpirsch** [comment]
Hi @ivarref @Jolg42
since 0.8.0, font.getKerningValue no longer uses the GPOS table, only the kern table.
0.8.0 uses the GPOS table more accurately, with script and language information.
In order to get the kerning value, you need to

1. get the kerning lookup tables for the current script and language
`kerningLookups = font.position.getKerningTables('DFLT')`
note that 'DFLT' script does not exist in all fonts. Use `font.position.getDefaultScriptName();` to get a better default value.
2. call `font.position.getKerningValue(kerningLookups, 56, 56)` which returns 16 as expected.

This is done in `Font.prototype.forEachGlyph`, called by all path and draw methods.

**Comment by Jolg42** [comment]
Thanks @fpirsch for the explanation!
I think it would make sense to update the README with an example then.

**Comment by ivarref** [comment]
> It is not anymore the entry-point to get kerning information.

Thanks for this clarification @fpirsch . I have not read the code to know if there is a good reason for this change, but as a user of the API this seems harder using the prescribed method in 0.8.0 than in 0.7.3. Would it be possible to be backwards compatible --- or does that not make sense?

Improved documentation would be good, but backwards compatibility would be better?

PS: I also noticed that `glyph.name` is undefined for the new Roboto Black font in 0.8.0. Example code:

```javascript
var opentype = require('opentype.js');

function showKerningValue(file) {
	var font = opentype.loadSync(file);
	var glyphT = font.charToGlyph('T');
        console.log("glyph name:", glyphT.name);
}

showKerningValue('./old.ttf');
showKerningValue('./new.ttf');
```
has output
```
glyph name: T font: ./old.ttf
glyph name: undefined font: ./new.ttf
```

**Comment by fpirsch** [comment]
`font.getKerningValue` was an over-simplification, even if it "kind of" worked until 0.7.3.
However I overlooked the effects on this API. I think I can restore the previous behavior.

**Comment by fpirsch** [comment]
With #335 `font.getKerningValue` uses sensible defaults to work exactly as before.

**Comment by ivarref** [comment]
Thanks a bunch!
