### ISSUE TITLE
Elliptical Arc can I disable in SVG out? Can I disable repeat end points?

### ISSUE THREAD

**Issue by nanjizal** [nodebox/opentype.js#334]
Have been working on a WebGL contour triangle engine so was excited when I found your library as it  seems ideal to generate path data I can pass to my engine for testing so tried using  Dan's wrapper https://danmarshall.github.io/google-font-to-svg-path/ to create some svg.

My problem is that I have not yet implemented Elliptical Arcs and I wanted to be sure I needed them and for fills they maybe a problem.
https://github.com/nanjizal/Trilateral/blob/master/src/trilateral/justPath/SvgPath.hx#L160

Is it possible with your library to only output bezier curves and avoid Elliptical from the svg output, I could not work out where to modify that, I could not see it in your Path code, and I could not see it in Danmarshall's code which seems mostly a wrapper round yours?

Another issue I am having is that poly2trihx fill library seems unhappy about repeated points which happens at the end of a letters, I can extract them quite easily if I don't join letters together... but if I do then it's more tricky. Is there an option to disable that or do I need to deal with that?

The elliptical arc means that if I render the fills with hxPolyK at moment the 'o' does not get rendered at all, polyK does not deal with holes but seems more tolerant, the white outline is my Trilateral library still WIP, I am using haxe Kha cross toolkit but have similar demos working direct with haxe js WebGL, the clip is from the browser.

<img width="475" alt="destination_in_time_both" src="https://user-images.githubusercontent.com/20134338/37429214-97839ae0-27c6-11e8-96ad-d063cb9c4eb5.png">

( In case your curious this is my current classes, you can switch to FillOnly from Fine if I just need fill data.
https://gist.github.com/nanjizal/b9909a6ed84bc8805e2e439e0ee7cc9a )

I realize it's not that practical rendering text as triangles, but feasible for a few letters.

**Comment by danmarshall** [comment]
Hi @nanjizal - this is probably not an opentype.js issue. In my code, I optimize for arcs. Can you close the issue here and open a new one at https://github.com/danmarshall/google-font-to-svg-path ? 👍

**Comment by nanjizal** [comment]
oh ok sorry Dan I did look through your code and mostly it seemed to use two other MIT projects
