### ISSUE TITLE
Does both export to TrueType and Opentype work?

### ISSUE THREAD

**Issue by orklann** [nodebox/opentype.js#341]
I like to use `opentype.js` to open OpenType font, and export it as a TrueType one, can I do this at the moment?

**Comment by minsikim** [comment]
adding to above question,
can `opentype.js` save changed fonts to local file system?
not using `font.download()`
(I'm trying to use it as a desktop app)

**Comment by Jolg42** [comment]
@orklann OpenType.js can read .otf .ttf .woff files but only exports .otf files as of today

**Comment by Jolg42** [comment]
@minsikim Yes indeed! Just use `font.toArrayBuffer()` and store that buffer, you can check how works the download function and adapt it to your needs. https://github.com/nodebox/opentype.js/blob/3a387f38f5fc18c8e6f7faddd6527ffddc36bf75/src/font.js#L498
