### ISSUE TITLE
Font parsing fails if it doesn't contain cmap for platform ID 3 (Windows)

### ISSUE THREAD

**Issue by dhowe** [nodebox/opentype.js#348]
I'm trying to debug the failure of [this font](https://s3-us-west-2.amazonaws.com/assets.editor.p5js.org/5980e1bf3c8046371e6cbc08/ffc75c61-1fd1-47b5-8cac-735505f7c5cb.ttf), which outputs "Error: No valid cmap sub-tables found" in the [font-inspector](https://opentype.js.org/font-inspector.html) and fails in our js code.

Any idea why this is failing to parse ?

The relevant data  (I think) from the file follows (full xml [here](https://gist.github.com/dhowe/1bf8ff1064eee3f96589d8ae9b1da343)).

![image](https://user-images.githubusercontent.com/737638/41276253-4a9fc5c4-6e56-11e8-8b25-1d2566688249.png)

**Comment by Jolg42** [comment]
Hi @dhowe is that xml coming from SynalizeIt?

Also, it would be easier to debug if you could send a link to the font file :)

**Comment by dhowe** [comment]
Yes, correct. And the font is linked in the first line of the ticket...

**Comment by Jolg42** [comment]
Got it! 😅

I tried to validate it through Microsoft's Font Validator and there are a lot of red flags...!
For the cmap table there is indeed something weird "The table does not contain any Microsoft subtables" 
![screenshot 2018-06-12 at 11 11 21](https://user-images.githubusercontent.com/1328733/41281378-8242dc5c-6e31-11e8-8f5d-4213c7a2e83d.png)

It looks like this font only contains information for [the platform ID 0](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#unicode-platform-platform-id--0)
![screenshot 2018-06-12 at 11 16 42](https://user-images.githubusercontent.com/1328733/41281623-2135667c-6e32-11e8-81af-e2b07d959e14.png)

And OpenType.js as of today[ only reads platform ID 3](https://github.com/nodebox/opentype.js/blob/0e16508f2aaebb5db15589b3d723bcde2466d618/src/tables/cmap.js#L90) as it's present in all fonts normally

**Comment by Jolg42** [comment]
Also, I don't know where's the font from but an updated version should be available somewhere. You could try to find that updated version and try again.

**Comment by Jolg42** [comment]
Closing as we don't support fonts without platform ID 3 (PR welcome!)

**Comment by dhowe** [comment]
thanks for checking

**Comment by dhowe** [comment]
Interesting to note that the above font is included in the default set for OS X (High) Sierra

**Comment by Jolg42** [comment]
I also think we should support it considering the scale.
Until now all fonts even distributed by Apple had the platform ID for Windows, I guess we can call that a breaking change from them...!

**Comment by Jolg42** [comment]
Should be fixed in [0.9.0](https://github.com/nodebox/opentype.js/tree/0.9.0) thanks to @moyogo 😉
