### ISSUE TITLE
Processing Meriweather-700-italic throws an error

### ISSUE THREAD

**Issue by astoilkov** [nodebox/opentype.js#349]
I am processing some variants of the Meriweather font. However, the 700 weight italic version is the only one throwing an error.

## Steps to Reproduce (for bugs)
You can download the attached font and just initialize the font with opentype
[Merriweather-700-italic.woff.zip](https://github.com/nodebox/opentype.js/files/2110505/Merriweather-700-italic.woff.zip)

## Context
I have tried to report the issue in the [library you are calling internally](https://github.com/devongovett/tiny-inflate/issues/4) but no one responded.

## Your Environment
* Version used: Latest
* Font used: Meriweather 700 italic
* Browser Name and version: Node.js
* Operating System and version (desktop or mobile): macOS

**Comment by Jolg42** [comment]
It looks like there is one error in that font:

`ERROR | The "head" table checkSumAdjustment (0x49a12a1c) does not match the calculated checkSumAdjustment (0x8dfcfa15).`

Checked with http://validator.fontbureau.com/validate

**Comment by astoilkov** [comment]
You mean we should report the font to Google?

**Comment by Jolg42** [comment]
Also as the problem is also linked with `tiny-inflate` I guess I won't be able to help more than:
- You could try to recreate a woff (either from a .ttf or .otf or converting it to .ttf first)
- Or find another version of that font in .woff that works.

**Comment by Jolg42** [comment]
I think you should report it, because it is weird that there is an error in this font.
