### ISSUE TITLE
Word wrap

### ISSUE THREAD

**Issue by danmarshall** [nodebox/opentype.js#352]
Is word wrapping possible?

To implement it, I suppose that the API would need a "maximum width" parameter passed in.

**Comment by axkibe** [comment]
It's not hard to do when you are okay with ragged right paras, a while I go I pull requested getAdvanceWidth() into opentype.js to be able to exactly do this:

See 
https://github.com/axkibe/linkloom/blob/master/src/visual/para.js#L194
for an implement to it. At this point it only stores x/y values where to put tokens.

Keyline is this regular expression to split the sentence into chunks ("words") while keeping white spaces intact:
```const reg = ( /(\S+\s*$|\s*\S+|^\s+$)(\s?)(\s*)/g );````

For opentype.js it is argueable if this should be in the library. The maintainers would have to decide. On the desktop this another library (pango) where freetype only does glyphs.

You might also want to cache the opentype.js rendering results for chunks.

Of course this a primitive version, word wrapping can be done way more sophisticated, first that code is not aware of syllabification that can be taken into account. Secondly it does it like MS-Word or most Browsers filling each line up until each line is full. Different for example LaTeX which would arrange words that way so the square of the white distance on the right is as small as possible.

And of course if you'd like a justified paras things get a somewhat more complicated as the space between chunks is stretched or shrinked.

**Comment by Jolg42** [comment]
Hi!

So I remember that there is something that was done a while back:
https://github.com/Jam3/opentype-layout

Implementing it directly in OpenType.js could be nice too but you will have to do the PR as maintainers are busy right now.

I suggest you check opentype-layout first and see if it's something that could work for you 😉

**Comment by axkibe** [comment]
That code breaks the text into chars and then into glyphs... that would be my biggest issue it destroying all ligatures.

**Comment by Jolg42** [comment]
Indeed...!
It was done before implementing ligatures I think so it wasn't a problem at that time.

**Comment by danmarshall** [comment]
Thanks for the guidance @Jolg42 ! I will try the opentype-layout project. 👍

**Comment by danmarshall** [comment]
opentype-layout [works well](https://maker.js.org/playground/?script=makerjs-wrap-text), thanks!
