### ISSUE TITLE
Substitutions not exported from the dist file

### ISSUE THREAD

**Issue by mattlag** [nodebox/opentype.js#353]
## Expected Behavior

I'm trying to use the new Substitution behavior.  In my code I do something similar to the substitution test example:

`let ligatureSubstitutions = new opentype.Substitution(font);`

## Current Behavior

But I get the error:
` TypeError: opentype.Substitution is not a constructor`

And looking into the window object, window.opentype.Substitution is not there.  The rest of the opentype global objects are there (Font/Glyph/BoundingBox/Path)

## Possible Solution

I'm not sure how the whole project is bundled, but I think the Substitution object needs to be added to the exports object.  This is from the bottom of the dist file:

```	exports.Font = Font;
	exports.Glyph = Glyph;
        exports.Path = Path;
	exports.BoundingBox = BoundingBox;
        exports.Substitution = Substitution;  // Should this be added here?
	exports._parse = parse;
	exports.parse = parseBuffer;
	exports.load = load;
	exports.loadSync = loadSync;

	Object.defineProperty(exports, '__esModule', { value: true });
```

## Your Environment

* Version used: 0.9.0
* Font used: Created from scratch (Glyphr Studio)
* Browser Name and version: All
* Operating System and version (desktop or mobile): Windows 10
* Link to your project: https://github.com/glyphr-studio/Glyphr-Studio-1

**Comment by fpirsch** [comment]
Hi @mattlag !
You don't need to instantiate this object, it's already done for you in `font.substitution`.
For standard ligatures you don't even need it, because they are on by default.

**Comment by mattlag** [comment]
Ah! Thanks - I was trying to go off the test case example... but this makes sense as well, and it seems to be saving a font with ligatures.  I might do a quick pull request to add this to the readme.

I'm putting my ligature glyphs in the Unicode Private area (above U+E000) - but when I open my resulting OTF, I get this error from FontForge:

![image](https://user-images.githubusercontent.com/5897669/43680255-ea23f0e4-97ea-11e8-8929-9397f41ef2e4.png)

So it seems like somewhere the maximum glyph isn't being calculated?  Is there a better / recommended way of doing this?

**Comment by fpirsch** [comment]
The Glyph ID is just an index inside the font, it's not the unicode codepoint. Remember the same glyph can be used to render multiple characters.

**Comment by mattlag** [comment]
Okay, thanks - looking into it further!  I'm going to close this issue, since it's not an issue :-)  Thank you for the help!

**Comment by mattlag** [comment]
Just for posterity, if anybody finds this in the future: for adding ligatures like this;
`font.substitution.addLigature('liga', {sub: [1, 2, 3], by: 4});`
those numbers are the **font glyph index** - I was under the impression they were the decimal version of the Unicode code point.  Previous to implementing ligatures, I had just been using the decimal code point for both `glyph.unicode` and `glyph.index` - but not anymore 😃 glyph indexes seem to need to be sequential, otherwise they cause errors once the OTF is saved.
