### ISSUE TITLE
glyphs need to be sorted before the font is generated, otherwise it gets corrupted

### ISSUE THREAD

**Issue by louisremi** [nodebox/opentype.js#75]
When trying to generate a font, the glyphs need to be sorted, using a simple font.glyphs.sort() before converting it to a buffer. Otherwise the font gets corrupted.

(Sorry for this incomplete bug report, I've got to file it real quick before leaving the office, will try to produce reduced test-case tomorrow)

**Comment by fdb** [comment]
Closing this for now, can't reproduce.
