### ISSUE TITLE
How to get ascent and descent

### ISSUE THREAD

**Issue by joshmarinacci** [nodebox/opentype.js#80]
I'm implementing a Canvas compatible API and I would like to get the ascent and descent of a font.  I can calculate the min and max y values for a particular run of text, but then it will be dependent on that particular text. For example, 'GG' would return different results than 'Gg'.  Is there a way to get the heights for the entire font instead of just particular glyphs?

**Comment by jagi** [comment]
But do you have any idea how to convert those values to real ascent and descent values for given font size? I'm thinking about creating poly fill for `measureText` that uses opentype.js.

**Comment by jagi** [comment]
Ok I've found the solution:

```js
var font;
opentype.load('url.ttf', function (err, f) {
  font = f;
});

/* ... */

var measure = ctx.measureText('Test');
measure.fontBoundingBoxAscent = font.ascender / font.unitsPerEm;
measure.fontBoundingBoxDescent = font.descender / font.unitsPerEm;
```

**Comment by fdb** [comment]
Sorry for the late reply. Your answer is indeed correct – all font geometry values are in `unitsPerEm`, so you have to scale them by that value.
