### ISSUE TITLE
Some font characters lead to wrong display

### ISSUE THREAD

**Issue by georg-paul** [nodebox/opentype.js#85]
I have uploaded two fonts ("Neris Light" and "Leaque Gothic Regular") to your glyph inspector. Please see the attached screenshots.

Your can reproduce the error there:
Font: Neris Light, Incorrect character "t" (unicode 0074)
Font: Leaque Gothic Regular, Incorrect character "D" (unicode 0044)

The font files are not broken generally.

You can download the free fonts here:
http://www.fontsquirrel.com/fonts/neris
http://www.fontsquirrel.com/fonts/league-gothic

Please let me know if you need more information.

![glyph-inspector-font-leaque-gothic](https://cloud.githubusercontent.com/assets/1918714/5612022/b4b76d64-94ce-11e4-9345-6aedc9eb36fd.png)
![glyph-inspector-font-neris](https://cloud.githubusercontent.com/assets/1918714/5612023/b4bc479e-94ce-11e4-888e-2eef088621d8.png)

**Comment by fdb** [comment]
Strange – it reports some of the coordinates as `NaN` – Not A Number. Will investigate, thanks for the report.

**Comment by tshinnic** [comment]
There are unsupported Type 2 CharString operators in at least the "League Gothic Regular" font file, and I wouldn't doubt this is true of both.

Adding the console.log line below does display the message "saw unsupported operator 1237", which equates to the 'flex1' operator.  Having worked on some other code derived from openfont.js I knew that there were potential problems with leftover items on the stack.  In this case the unhandled operator left a bunch of stack values.  

By adding the stack reset line as below the unused/unusable stack values are thrown away.  The resulting displayed 'D' is not quite so distressed.
```javascript
      case 12: // escape
          v = code[i];
          console.log('saw unsupported operator %d', 1200+v);
          stack.length = 0;
```
![opentype_85_league_d_1](https://cloud.githubusercontent.com/assets/842881/6015141/92b92e36-ab36-11e4-8bce-c2f0acdc8ad0.png)

Of course the result is very likely not as desired, just less bad.  :grin: 

By your having provided a font file with CFF CharStrings containing this additional mysterious operator maybe @fdb or I can attempt a simulation of the 'flex1' operator.  (The docs read just dreadful!)

BTW: What program(s) did you use to generator the OTF font files?

OBTW: Here are my notes trying to line up the CFF instructions with what was previously emitted:
```
  M x=40  y=0                                 22  hmoveto      stack: (1) [40]
  L x=40  y=735                                7  vlineto      stack: (2) [735, 85]
  L x=125 y=735                                                                 *
  C x=308 y=659 x1=225 y1=735 x2=279 y2=715   31  hvcurveto    stack: (5) [100, 54, -20, -56, 29]
  C x=340 y=367 x1=336 y1=603 x2=340 y2=511   26  vvcurveto    stack: (5) [28, -56, 4, -92, -144]
  C x=308 y=76  x1=340 y1=223 x2=336 y2=132   30  vhcurveto    stack: (5) [-144, -4, -91, -28, -56]
  C x=125 y=0   x1=279 y1=20  x2=225 y2=0     27  hhcurveto    stack: (5) [-56, -29, -54, -20, -100]

  M x=148 y=108                               21  rmoveto      stack: (2) [23, 108]
  C x=217 y=148 x1=185 y1=108 x2=206 y2=112   31  hvcurveto    stack: (5) [37, 21, 4, 36, 11]
  C x=227 y=226 x1=222 y1=165 x2=226 y2=191
  C x=228 y=368 x1=228 y1=261 x2=228 y2=308    8  rrcurveto    stack: (6) [5, 17, 4, 26, 1, 35]
                                            1237  flex1        stack: (11) [1, 35, 0, 47, 0, 60, 0, 60, 0, 47, 35]
  C x=263 y=474 x1=228 y1=428 x2=228 y2=475    8  rrcurveto    stack: (6) [-1, 34, -4, 26, -5, 18]
  C x=341 y=NaN x1=297 y1=470 x2=323 y2=465
  C x=272 y=NaN x1=330 y1=NaN x2=309 y2=NaN   27  hhcurveto    stack: (5) [35, -11, -21, 4, -37]
  Z 
```

My notes of what the 'D' glyph (GID#18) CFF instructions were:
```
 on operator   10  callsubr     stack: (2) [84, 10]
 on operator   10  callsubr     stack: (2) [84, -29]
 on operator   10  callsubr     stack: (2) [84, -14]
 on operator   11  return       stack: (3) [84, 0, 735]
 on operator    1  hstem        stack: (3) [84, 0, 735]
 on operator   11  return       stack: (0) []
 on operator   11  return       stack: (1) [148]
 on operator    3  vstem        stack: (2) [148, 79]

 on operator   22  hmoveto      stack: (1) [40]

 on operator   10  callsubr     stack: (1) [-51]
 on operator    7  vlineto      stack: (2) [735, 85]

 on operator   10  callsubr     stack: (1) [-34]
 on operator   31  hvcurveto    stack: (5) [100, 54, -20, -56, 29]
 on operator   26  vvcurveto    stack: (5) [28, -56, 4, -92, -144]
 on operator   30  vhcurveto    stack: (5) [-144, -4, -91, -28, -56]
 on operator   27  hhcurveto    stack: (5) [-56, -29, -54, -20, -100]
 on operator   11  return       stack: (0) []

 on operator   21  rmoveto      stack: (2) [23, 108]

 on operator   10  callsubr     stack: (1) [-53]
 on operator   31  hvcurveto    stack: (5) [37, 21, 4, 36, 11]
 on operator    8  rrcurveto    stack: (6) [5, 17, 4, 26, 1, 35]
 on operator 1237  flex1        stack: (11) [1, 35, 0, 47, 0, 60, 0, 60, 0, 47, 35]
unhandled operator 1237 flex1         stack: [1, 35, 0, 47, 0, 60, 0, 60, 0, 47, 35]
 on operator    8  rrcurveto    stack: (6) [-1, 34, -4, 26, -5, 18]
 on operator   27  hhcurveto    stack: (5) [35, -11, -21, 4, -37]
 on operator   14  endchar      stack: (0) []
```

**Comment by fdb** [comment]
Hi,

The issue is fixed for most characters, but some characters still use different `flex` operators, which are not yet supported.

**Comment by miguelsousa** [comment]
@tshinnic could you share the code (in a Gist or something) you used for outputting the notes above? It looks like a very good solution for debugging the stack.

**Comment by tshinnic** [comment]
Here it is in a gist ["opentype.js 2-byte decoding and add operator/operand decode tracing"](https://gist.github.com/tshinnic/64f70567ed8d4cdc2af8)  formatted as a git patch.  As the description says, this is actually two different things: combine the 1-byte and 2-byte operator decoding, and add operator/operand decode tracing.

@fdb should advise on what parts of this would be acceptable for inclusion, and in what form...

**Comment by fdb** [comment]
Super useful! Anything to make debugging CFF easier :-)

I'll look at this on Monday.
