### ISSUE TITLE
Add support for CID-keyed fonts

### ISSUE THREAD

**Issue by miguelsousa** [nodebox/opentype.js#90]
As @tshinnic discovered, [opentype.js doesn't yet support CID fonts](https://github.com/nodebox/opentype.js/pull/89#issuecomment-72994757). This kind of OpenType fonts is the norm for CJK (Chinese/Japanese/Korean) fonts. [Source Han Sans](https://github.com/adobe-fonts/source-han-sans/releases) is the perfect font family to test with.
/cc @kenlunde

**Comment by fdb** [comment]
It seems performance is going to be an issue as well, simply because of the large character sets of CJK fonts. I'll think about lazy loading the font.

**Comment by kenlunde** [comment]
Keep in mind that Source Han Sans represents the extreme end of the "number of glyphs" spectrum for CJK fonts because the number of glyphs is at the architectural limit of 65,535 glyphs. Typical CJK fonts have less than 30K glyphs, which many at or slightly below 10K glyphs.

**Comment by tshinnic** [comment]
I'm making my own code neater for the CID font case, and then I'll try to jam the equivalent into opentype.js.  The high-level TopDict+PrivateDict in usually coded as there can be only one, but at one point there could be / could have been multiple fonts in a CFF font and thus multiple TopDicts.  That almost exactly duplicates the needed handling of FDArray.  I'm trying to make just one routine to handle the "array of TopDicts" situation and apply to both situations.  I hate duplicating code...

**Comment by axkibe** [comment]
This can be closed IMO as recently fixed.
