### ISSUE TITLE
Support for reading and writing Ligatures in a Font

### ISSUE THREAD

**Issue by mattlag** [nodebox/opentype.js#96]
I'm not sure what the best way to do this would be, from the Font object perspective.  Extend the Glyph object? Create a peer to Font.glyphs that is Font.ligatures?

- create a new Ligature
- ask the Font object to return a Glyph object for a ligature

Anyway, just putting this on the radar.

**Comment by davelab6** [comment]
This is the other side of the #95 coin, about adding support for GSUB rather than GPOS :) 

I think ideally opentype.js will port https://github.com/typesupply/feaTools to js

**Comment by mattlag** [comment]
Ah, I didn't think about ligatures with their own single Unicode value.  That is a great idea.

**Comment by davelab6** [comment]
http://en.wikipedia.org/wiki/List_of_precomposed_Latin_characters_in_Unicode

Versus https://github.com/twardoch/ttfdiet :)

**Comment by Jolg42** [comment]
Note : The GSUB table is now readable / writeable 🎊

**Comment by mattlag** [comment]
Thank you, @Jolg42!
